### ISSUE TITLE
OpenCL 2.2 CTS: can provide spirv10_2015.11.25.zip to non Khronos members?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/OpenCL-CTS#1]
reading OpenCL-CTS/readme-spir-v-binaries.txt says:

```
To run the 2.2 conformance tests test suite for the C++ features you need need 
SPIR-V binaries.
can be picked from:
https://cvs.khronos.org/svn/repos/OpenCL/trunk/Khronos/spirv/spirv10_2015.11.25.zip

```
but that link can't be accessed for a non Khronos user so can upload this file?
I say that because txt file also says this:
`Alternatively you can check out and build all of the below repositories.`
problem is all this links also are to Khronos members and these projects altough exist on github are missing required branches so note I also asked 
SPIRV-LLVM (https://github.com/KhronosGroup/SPIRV-LLVM/issues/218) 
and 
libclcxx (https://github.com/KhronosGroup/libclcxx/issues/15) 
projects on github to be updated..

**Comment by kepatil** [comment]
Thanks for looking. This is most likely a remnant from when the CTS was not made public. I'll get it sorted out.

Meanwhile, please try the [CTS framework](https://github.com/KhronosGroup/OpenCL-CTS-Framework) which should be able to locate and download required stuff automatically.

**Comment by oscarbg** [comment]
thanks @kepatil..
really didn't try to build the CTS yet..
will try the CTS framework but anyway seems SPIRV-LLVM and libclcxx github projects need to be updated for final OpenCL 2.2 compatibility..

**Comment by InBetweenNames** [comment]
@oscarbg The CTS framework contains a buildsystem that takes care of all of that for you.  Send me a message if you need help setting it up.

**Comment by kepatil** [comment]
I have added the SPIR-V binaries using [LFS](https://git-lfs.github.com/) and updated the readme to point to the new location, in commit https://github.com/KhronosGroup/OpenCL-CTS/commit/252b514ef443f97f38ff15641bbebbf42b3c56a9. Closing the issue.

**Comment by oscarbg** [comment]
thanks..
