### ISSUE TITLE
Non-existing version vloada_halfn is being tested

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/OpenCL-CTS#1002]
The issue was discovered in KhronosGroup/SPIRV-LLVM-Translator#765

Basically, the following code tries to call `vloada_half` function, which doesn't seem to be defined neither in OpenCL 1.2 or OpenCL 2.0. Am I missing something?

https://github.com/KhronosGroup/OpenCL-CTS/blob/615ab64db5327e49129c4511102c23d9c810cf5e/test_conformance/half/Test_vLoadHalf.cpp#L40-L45

**Comment by alycm** [comment]
There was also a Khronos internal issue filed about this yesterday (259).

I think there are essentially two possible actions.

1. Delete from the CTS, the size 1 variant was only ever in OpenCL 1.1 and that was almost certainly a mistake.
2. Add it to the specification, on the basis that all implementations >= 1.1 must be implementing it to pass the CTS, so there could be code out in the world that depends on it.

A complication of (2) is that if there is vloada_half of size 1 in the specification then surely vstorea_half of size 1 should be there too -- but that doesn't have the accidental CTS guarantee that implementations already have it.

**Comment by bashbaug** [comment]
We just ran into this issue again.  Here's what I propose we do:

1. Create a CTS PR that removes the special-case code for `vloada_half` described above.  This will make the tests consistent with the spec, that does not include a scalar `vloada_half`.  I will create this PR.
2. Create a spec issue to clarify / discuss whether `vloada_half` and/or `vstorea_half` really belongs in the spec.  I will create this spec issue also.

Depending how the spec issue gets resolved we'll either do nothing (spec is correct, `vloada_half` does not need to be supported or tested by the CTS tests, though implementations may still support it for compatibility if desired), or we'll add it back to the spec, CTS tests, SPIR-V LLVM Translator, etc.

Sound good?

**Comment by AlexeySachkov** [comment]
> Sound good?

Sounds good to me, thanks @bashbaug

**Comment by bashbaug** [comment]
Since we've merged #1293 I think this issue can be closed now?
