### ISSUE TITLE
Reduce number of compilations in buffers suite

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#1020]
Many tests in the buffer suite loop over a combination of flags for a number of data types (e.g. https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/buffers/test_buffer_read.cpp#L652). Programs and kernels are re-compiled in the inner loop which leads to a lot of time wasted recompiling the same programs. Swapping the two loops and pulling compilations out of the inner loop would result in a 5x reduction of the overall execution time for the suite (seems dominated by compilation time).

**Comment by ellnor01** [comment]
I'm working on this
