### ISSUE TITLE
rw_image_access_qualifier incorrect check for optional feature

### ISSUE THREAD

**Issue by ijkmn** [KhronosGroup/OpenCL-CTS#1024]
// test_rw_image_access_qualifier.cpp
 // Support for read-write image arguments is required for an
    // or 2.X device if the device supports images. In OpenCL-3.0
    // read-write images are optional. This test is already being skipped
    // for 1.X devices.
    if (get_device_cl_version(device_id) >= Version(3, 0))
    {
        cl_uint are_rw_images_supported{};
        test_error(
            clGetDeviceInfo(device_id, CL_DEVICE_MAX_READ_IMAGE_ARGS, <= **should be   CL_DEVICE_MAX_READ_WRITE_IMAGE_ARGS**
                            sizeof(are_rw_images_supported),
                            &are_rw_images_supported, nullptr),
            "clGetDeviceInfo failed for CL_DEVICE_MAX_READ_IMAGE_ARGS\n");
        if (0 == are_rw_images_supported)
        {
            return TEST_SKIPPED_ITSELF;
        }
    }

**Comment by nikhiljnv** [comment]
Most of these checks were replaced with checkForReadWriteImageSupport as part of https://github.com/KhronosGroup/OpenCL-CTS/pull/965/. Looks like this was missed out.

**Comment by ijkmn** [comment]
fixed by #1072
