### ISSUE TITLE
Image helpers contain unused "obsolete format" code

### ISSUE THREAD

**Issue by StuartDBrady** [KhronosGroup/OpenCL-CTS#1044]
The image helpers contain unused "obsolete format" code which should possibly be removed. This code is guarded by the **OBSOLETE_FORMAT** and **OBSOLETE_FORAMT** macros (note the typo in the latter) as listed below:

```
$ git grep OBSOLETE_FOR | uniq -c
      6 test_common/harness/imageHelpers.cpp:#ifdef OBSOLETE_FORAMT
      1 test_common/harness/imageHelpers.h:#ifdef OBSOLETE_FORMAT
      1 test_conformance/images/common.cpp:#ifdef OBSOLETE_FORAMT
```

**Comment by svenvh** [comment]
This has been fixed now by #1776
