### ISSUE TITLE
printf is very undertested

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/OpenCL-CTS#1058]
The printf tests don't cover

- multiple arguments
- no arguments
- data before format specifier

**Comment by franz** [comment]
It should also cover more special cases. E.g. both of these two: 

`printf("")`
`printf("%s", "")`

.. should print an empty string. Furthermore, i think the test of printf with NaN is problematic. This test

`{"%f","sqrt(-1.0f)"},`

expects a `-nan` to be printed, however it makes two assumptions, 1) that the sqrt operation returns a negative nan (not positive), and 2) that printf prints the sign of the nan. AFAICT, both are incorrect; the IEEE 754 does not assign any meaning to sign bit of the NaN, and printing out the sign is optional.

**Comment by pjaaskel** [comment]
`printf("%%")` could be interesting to test as well.

**Comment by pjaaskel** [comment]
Can we put this to the "mobica-backlog"? Thanks!

**Comment by shajder** [comment]
Based on previous discussion and spec investigation below is a work plan to extend the current framework of printf tests. I will appreciate any suggestions and corrections:

New set of printf tests with multiple arguments. It will take into account:
- [ ]  various types of arguments test
- [ ]  no arguments test
- [ ]  additional data before/after format specifiers

New tests related to printout formatting:
- [ ] verification of `space` flag prefixing
- [ ] verification of `zero` flag padding

Corrections for previous tests:
- [ ] Complementing vector tests to take into account all vector variants, conversions specifiers and length modifiers
- [ ] Complementing all floating precision printf tests with missing conversions %a, %A, %F
- [ ] Complementing string tests with special cases and precision number
- [ ] Complementing all non-vector conversions with length modifiers tests
- [ ] Correction for nan/inf printf tests
