### ISSUE TITLE
2.0 feature is optional for OCL 3.0

### ISSUE THREAD

**Issue by ijkmn** [KhronosGroup/OpenCL-CTS#1068]
in test_CL_DEVICE_OPENCL_C_VERSION_features function, 2.0 features should be optional for 3.0, 

    const Version clc_version = get_device_cl_c_version(device);
    if (clc_version >= Version(2, 0))
    {
        bool has_all_OpenCL_C_20_features =
            features.supports__opencl_c_atomic_order_acq_rel
            && features.supports__opencl_c_atomic_order_seq_cst
            && features.supports__opencl_c_atomic_scope_device
            && features.supports__opencl_c_atomic_scope_all_devices
            && features.supports__opencl_c_device_enqueue
            && features.supports__opencl_c_generic_address_space
            && features.supports__opencl_c_pipes
            && features.supports__opencl_c_program_scope_global_variables
            && features.supports__opencl_c_work_group_collective_functions;

        if (features.supports__opencl_c_images)
        {
            has_all_OpenCL_C_20_features = has_all_OpenCL_C_20_features
                && features.supports__opencl_c_3d_image_writes
                && features.supports__opencl_c_read_write_images;
        }

        test_assert_error(
            has_all_OpenCL_C_20_features,
            "At least one required OpenCL C 2.0 feature is missing!");
    }

    return TEST_PASS;

**Comment by FranklandJack** [comment]
Hey,

I think the code snippet you pasted is correct in its current state and this branch should be skipped if the optional features are not supported.

I took a look at the source for [`get_device_cl_c_version`](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/kernelHelpers.cpp#L1712), and it uses the [`CL_DEVICE_OPENCL_C_VERSION`](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_DEVICE_OPENCL_C_VERSION) query to query for the OpenCL C version on all devices with versions greater than 1.0. From the spec it says that `CL_DEVICE_OPNECL_C_VERSION` returns the most recent backward compatible OpenCL C version supported by the device:

> Because OpenCL 3.0 is backwards compatible with OpenCL C 1.2, an OpenCL 3.0 device must support at least OpenCL C 1.2. An OpenCL 3.0 device may return an OpenCL C version newer than OpenCL C 1.2 if and only if all optional OpenCL C features are supported by the device for the newer version.

So, I think in the above code, `clc_version >= Version(2, 0)` will only ever be true for a 3.0 device if it supports all the optional features. I've tested this locally with a 3.0 device that optionally does not support these features and this branch is not taken.

**Comment by ijkmn** [comment]
got it, thanks
