### ISSUE TITLE
Add CTS for cl_ext_cxx_for_opencl

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-CTS#1075]
Implement testing as described in https://www.khronos.org/registry/OpenCL/extensions/ext/cl_ext_cxx_for_opencl.html, see section about the conformance tests.

**Comment by kpet** [comment]
@AnastasiaStulova I believe this can now be closed.

**Comment by AnastasiaStulova** [comment]
Sure, I thought it would work automatically.

**Comment by kpet** [comment]
For this to work automatically, you need to use a keyword (see https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)
