### ISSUE TITLE
Add support for Windows continuous integration using Appveyor

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#11]

**Comment by jrprice** [comment]
Travis CI have recently added (beta) support for Windows - might be worth looking at that instead of AppVeyor to (maybe) simplify things?
https://blog.travis-ci.com/2018-10-11-windows-early-release
(disclaimer: haven't tried it myself yet)

**Comment by kpet** [comment]
Nice :). I'll give this a go.
