### ISSUE TITLE
test_api get_sampler_info_compatibility failures

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#1103]
This test expects now that in case sampler is created by function `clCreateSampler` then `CL_SAMPLER_PROPERTIES` size is bigger than 0.
see: https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clGetSamplerInfo
```If sampler was created using clCreateSampler, or if the properties argument specified in clCreateSamplerWithProperties was NULL, the implementation must return param_value_size_ret equal to 0, indicating that there are no properties to be returned.```

**Comment by nikhiljnv** [comment]
Looks like the the normalized_coords , addressing_mode  and filter_mode that are passed as separate arguments to older clCreateSampler(), but are supposed to be passed as cl_sampler_properties to clCreateSamplerWithProperties() are counted as default properties and the size of properties returned by query is expected to match assuming these are part of list of sampler properties. Apparently, the spec does not explicitly mention what are bare minimum set of properties that need to be specified when creating a sampler via clCreateSamplerWithProperties(), but older API will return if any of the arguments above are not valid.

**Comment by nikhiljnv** [comment]
However, above does not go well with what spec says -
 If sampler was created using clCreateSampler, or if the properties argument specified in clCreateSamplerWithProperties was NULL, the implementation must return param_value_size_ret equal to 0, indicating that there are no properties to be returned.

So, the fix still seems to be valid.
