### ISSUE TITLE
cl12 cl21 cl22 - Lost fix - Add test for -cl-fp32-correctly-rounded-divide-sqrt to spir subtest.

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#112]
Looks like fix in spir tests is missed in opensource and present in internal gitlab

**Comment by alycm** [comment]
Do you happen to know if this fix is also missing from CL 1.2 and 2.0?

**Comment by gwawiork** [comment]
cl20_trunk contains these commits. cl12_trunk not - I send PR to fix this (a little bit different than cl21 and cl22 because math_brute_force.zip was already up to date)

**Comment by alycm** [comment]
Thank for the clarification about 2.0, and for creating the 1.2 PR.

**Comment by gwawiork** [comment]
After review changes needed in cl20 as well.

**Comment by alycm** [comment]
All four versions merged, so closing this issue.
