### ISSUE TITLE
test_vector_swizzle checking padding of 3-element vectors

### ISSUE THREAD

**Issue by stevec611** [KhronosGroup/OpenCL-CTS#1120]
test_vector_swizzle is checking that the value of the padding is unchanged in all 3-element destination vectors,
whether they are written using vstore or directly.
We (IMG) are wondering whether this is correct for the direct stores, or whether they are allowed to overwrite the padding?

**Comment by bashbaug** [comment]
> test_vector_swizzle is checking that the value of the padding is unchanged in all 3-element destination vectors,

This certainly wasn't my intent.

I'm guessing this part of the test is the problem?

```c
    // lvalue swizzles
    dst[index++].x = value.x;
    dst[index++].y = value.x;
    dst[index++].z = value.x;
    dst[index++].xyz = value;
    dst[index++].zyx = value;
```

When I wrote the test I was thinking that this would leave the unwritten channels unchanged, but it looks like at least Clang is loading the full vec3, modifying the channels on the left hand size, then writing back the full vec3 via a direct store: https://godbolt.org/z/MK4sxr

If this is the problem, would the alternate codepath work?  I haven't tried this (yet), but the idea is to do the final store with `vstore` instead.

```c
    t = dst[index]; t.x = value.x;
    vstore3(t, 0, (__global BASETYPE*)(dst + index++));
    // etc.
```

**Comment by stevec611** [comment]
The problem I thought I saw was that at:

`    if (buffer != reference)`

`buffer `and `reference `are vectors of scalars, not vectors of N-element vectors, so this will compare every scalar value in the buffer, whether it is a valid component of a vector or a padding component.     Shouldn't it skip the padding somehow for the non-vstore entries?  (For the vstore entries, checking the padding is unchanged is actually a Good Thing, IMO.)

**Comment by bashbaug** [comment]
Sorry about that, my reply was clearly unclear!

The idea behind the test was to always leave the padding unchanged so the simple check for equality is sufficient without any need to intelligently skip padding values.  This is not a strict requirement though, and we could make the check smarter if we decide to go in that direction.

The idea I mentioned above would use `vstore` to do all of the final stores, which would leave the padding unchanged in all cases.  This requires a bit of a kernel change in the vec3 cases, but the rest of the test would remain unchanged.

**Comment by stevec611** [comment]
Oh sorry, I completely misunderstood your reply!

Yes, your proposed change works for us.   I can prepare a PR for it, if that's ok with you?

**Comment by bashbaug** [comment]
> Yes, your proposed change works for us. I can prepare a PR for it, if that's ok with you?

Sounds good, let me know when it's ready and I'd be happy to review.  Thanks!
