### ISSUE TITLE
test_buffer buffer_write device memory leak

### ISSUE THREAD

**Issue by ijkmn** [KhronosGroup/OpenCL-CTS#1147]
test_buffer_write in test_conformance\buffers\test_buffer_write.cpp memory leak due to 'clMemWrapper buffers[10];' is asigned a new buffer each loop, but only free the buffers once when exit function.

v2021-02-01-00

**Comment by JohnKesapidesARM** [comment]
Fix in review here https://github.com/KhronosGroup/OpenCL-CTS/pull/1160
