### ISSUE TITLE
Image Helpers: implicit conversion from 'int' to 'float' changes value

### ISSUE THREAD

**Issue by mantognini** [KhronosGroup/OpenCL-CTS#1250]
Clang 12 (and possibly some older versions as well) report issues such as:

https://github.com/KhronosGroup/OpenCL-CTS/blob/657283799482433cc35d119ddab220dcad1f00aa/test_common/harness/imageHelpers.cpp#L2724-L2727

imageHelpers.cpp:2727:21: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-const-int-float-conversion]

Another occurence:

https://github.com/KhronosGroup/OpenCL-CTS/blob/657283799482433cc35d119ddab220dcad1f00aa/test_common/harness/imageHelpers.cpp#L2893-L2896

**Comment by jlewis-austin** [comment]
The first one looks like we're relying on the compiler's implementation of (int)2147483648.f to saturate back to 2147483647, which bypasses the purpose of the macro (ie, to provide RNE rounding, and saturation of out of range values). 32-bit integer conversions should promote to doubles for the comparisons, which would avoid the need for all the inexact magic going on in these.

**Comment by jlewis-austin** [comment]
Clang 10.0.4 reports this as `[-Werror,-Wimplicit-int-float-conversion]`, bypassing the current CMakeLists.txt workaround. I'm working on a fix for the root cause

**Comment by pierremoreau** [comment]
This was reported as #855. There was apparently some internal work on fixing it that was reported back in mid 2020, but there has been no update on that work since.

**Comment by jlewis-austin** [comment]
Sorry for the delay, I'm putting up a PR now
