### ISSUE TITLE
C11 Atomics: Memory model issue in atomic_flag

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#1270]
We have identified a possible memory model issue in the atomic_flag test - specifically in the local memory variants.

The way in which the kernel is currently written allows a compiler to re-order memory operations in such a way that leads to verification failures.

In the following snippet, the store to `oldValues` can be re-ordered so that it occurs after the call to `atomic_flag_clear_explicit`. This can then lead to test failures. The crux of the issue is that `oldValues` and  `destMemory` reside in separate memory regions so their memory orderings are seperate.

Passing in `CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE` to the release call of `atomic_work_item_fence` prevents this.

We have a patch ready for a PR, but looking for some initial feedback.

```C
bool set = atomic_flag_test_and_set_explicit(&destMemory[cnt], memory_order_relaxed, memory_scope_work_group);
atomic_work_item_fence(CLK_LOCAL_MEM_FENCE, memory_order_acquire, memory_scope_work_group);
if (!set)
{
    uint csIndex = get_enqueued_local_size(0) * get_group_id(0) + cnt;
    // verify that thread is the first visitor
    if (oldValues[csIndex] == 1000000000)
    {
        oldValues[csIndex] = tid; // set the winner id for this critical section
        stop = 1;
    }
    atomic_work_item_fence(CLK_LOCAL_MEM_FENCE, memory_order_release, memory_scope_work_group);
    atomic_flag_clear_explicit(&destMemory[cnt], memory_order_relaxed, memory_scope_work_group);
}
```

**Comment by kpet** [comment]
Not sure it's related but this reminds me of https://www.khronos.org/members/login/bugzilla/show_bug.cgi?id=15814

**Comment by Jeremy-Kemp** [comment]
Thanks for the link. Ironically we are also looking at a fence issue that has recently cropped up that looks eerily similar to that bug (still investigating however). The specific case linked though does appear to be separate from this issue as there is no mix of memory regions.

Always cautious when it comes to looking at memory model issues so if anyone has a view that is different to what I've laid out above, please let me know.

**Comment by jlewis-austin** [comment]
Also looks similar to #134.

**Comment by Jeremy-Kemp** [comment]
Thanks @jlewis-austin, at first glance that looks like an identical report.

**Comment by Jeremy-Kemp** [comment]
Duplicate of #134
