### ISSUE TITLE
Invalid test case for negative_get_platform_info

### ISSUE THREAD

**Issue by jlewis-austin** [KhronosGroup/OpenCL-CTS#1318]
The first test case for `test api negative_platform_info` 
https://github.com/KhronosGroup/OpenCL-CTS/blob/1f26e1d8ba372f4c638f9c0cdae7566e349b9b9a/test_conformance/api/negative_platform.cpp#L46 casts a `cl_device_id` to a `cl_platform_id` and expects an error of `CL_INVALID_PLATFORM`.

Per https://github.com/KhronosGroup/OpenCL-Docs/issues/482, implementations are only responsible for null-checking to check validity. This particular case actually dispatches correctly since the dispatch table is present--any valid CL object from the same platform would suffice for the platform argument. 

This test case should be deleted.

**Comment by kpet** [comment]
I think https://github.com/KhronosGroup/OpenCL-CTS/pull/1148 addresses this.

**Comment by jlewis-austin** [comment]
Thanks, I forgot about that one. The solution there looks like it needs more work to avoid re-introducing the incorrect null check test removed by https://github.com/KhronosGroup/OpenCL-CTS/commit/edc36b5d53c9b1cb6cd8f293fb461fc1151f1ace though?

Can we address this one separately while we work on that PR?

**Comment by kpet** [comment]
I think it's correct after a quick look. Given that 1148 is dragging on, I'm fine with inserting a separate PR ahead. It would be nice to reuse the relevant part of 1148 if possible.

**Comment by jlewis-austin** [comment]
@kpet I looked at using the relevant part of 1148, but was concerned about being able to cherry-pick this patch cleanly, and am thinking it would be a bit cleaner to separate the bug fix from the infrastructure change.
