### ISSUE TITLE
c11 atomic flag test is not correct in some cases

### ISSUE THREAD

**Issue by b-sumner** [KhronosGroup/OpenCL-CTS#134]
We're seeing the following failure when running the c11 atomic flag test:
...
       global atomic_flag declared in program, used in generic function, order_relaxed, scope_all_svm_devices...
                (thread count 1024, group size 256)
        local atomic_flag, order_acquire...
                (thread count 256, group size 256)
ERROR: Critical section 233 not visited
ERROR: Reference values did not validate!

The dumped kernel source contains this loop:

 for(cnt = 0; !stop && cnt < threadCount; cnt++) // each thread must find critical section where it is the first visitor
  {
    bool set = atomic_flag_test_and_set_explicit(&destMemory[cnt], memory_order_acquire);
    if (!set)
    {
      uint csIndex = get_enqueued_local_size(0)*get_group_id(0)+cnt;
      // verify that thread is the first visitor
      if(oldValues[csIndex] == 1000000000)
      {
        oldValues[csIndex] = tid; // set the winner id for this critical section
        stop = 1;
      }
      atomic_work_item_fence(CLK_LOCAL_MEM_FENCE, memory_order_release,memory_scope_work_group);
      atomic_flag_clear_explicit(&destMemory[cnt], memory_order_relaxed);
    }
  }

The problem here is that oldValues is in the global address space, but the atomics and fence are on the local address space.  Nothing is ordering the reads and writes to oldValues.  This is a data race.

**Comment by b-sumner** [comment]
One possible fix would make a local copy of oldValues at the start of the kernel, refer to the copy in the loop, and then copy back to global at the end of the kernel...with the appropriate barriers.

**Comment by gwawiork** [comment]
You are right. Your fix proposal sounds good.

**Comment by b-sumner** [comment]
Does someone else want to post a PR for this?  I may not be able to do this myself for a while yet.

**Comment by Jeremy-Kemp** [comment]
@b-sumner we've just seen this issue crop up as well.

I hadn't spotted this original issue, so filed #1270 (which I've since closed as a duplicate).

Our proposed fix which we have been testing was different to the proposal here, and is simply to change the fence to be `CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE`. Would that be acceptable?
