### ISSUE TITLE
math_brute_force floating-point accuracy error in test_spir 

### ISSUE THREAD

**Issue by hewj03** [KhronosGroup/OpenCL-CTS#135]
[Spir test](https://github.com/KhronosGroup/OpenCL-CTS/tree/cl22_trunk/test_conformance/spir) contains some math_brute_force kernels. The test compares SPIR and OpenCL C results bit-by-bit. However, for math_brute_force kernels, specification does not ask for SPIR and OpenCL C path to match bit-to-bit. 
[math_brute_force test](https://github.com/KhronosGroup/OpenCL-CTS/tree/cl22_trunk/test_conformance/math_brute_force) uses ULPs limits to tolerate small mismatches between OpenCL and reference results. Could we apply these ULPs limits to math_brute_force kernels in Spir test as well?

**Comment by alycm** [comment]
Hello, you've opened the MR against 2.1.  This could also be applied to 2.0 and 1.2.   I can test a 1.2 MR if that helps.

**Comment by alycm** [comment]
Thank for the additional branches, I have reviewed https://github.com/KhronosGroup/OpenCL-CTS/pull/152.

**Comment by hewj03** [comment]
Thanks for review. I've submitted a MR against 2.2 as well.

**Comment by alycm** [comment]
All four versions are merged, closing this issue.
