### ISSUE TITLE
C11 Atomics: Relaxed memory ordering in atomic_load tests

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#1370]
CTS can generate test cases that are invalid. We have noticed this in some of the `atomic_load` sub-tests.

In the kernel below, there is nothing preventing a compiler from re-ordering the `atomic_load_explicit`/`atomic_store_explicit` calls around the `atomic_fetch_add_explicit` call. It seems the intent of the atomic add is to gate the final load/store however we don't think that is strong enough to achieve the desired effect.

For this particular case, we don't think the structure of the kernel can be used due to the nature of `memory_order_relaxed`; making the test case (and others like it) invalid.

```C
/*  -cl-std=CL3.0 */
__global volatile atomic_uint finishedThreads = ATOMIC_VAR_INIT(0);
__global volatile atomic_int destMemory[1024] = {
    ATOMIC_VAR_INIT(255),
    ATOMIC_VAR_INIT(255),
    ....
    ATOMIC_VAR_INIT(255),
    ATOMIC_VAR_INIT(255)};
 
void test_atomic_function(uint tid, uint threadCount, uint numDestItems, volatile __global atomic_int *destMemory, __global int *oldValues)
{
    atomic_store_explicit(&destMemory[tid], tid, memory_order_relaxed, memory_scope_device);
    oldValues[tid] = atomic_load_explicit(&destMemory[tid], memory_order_relaxed, memory_scope_device);
}
 
__kernel void test_atomic_kernel(uint threadCount, uint numDestItems, volatile __global int *finalDest, __global int *oldValues)
{
    uint tid = get_global_id(0);
 
    test_atomic_function(tid, threadCount, numDestItems, destMemory, oldValues);
 
    // Copy final values to host reachable buffer
 
    if (atomic_fetch_add_explicit(&finishedThreads, 1u,
                                  memory_order_relaxed,
                                  memory_scope_work_group) == get_global_size(0) - 1) // last finished thread
        for (uint dstItemIdx = 0; dstItemIdx < numDestItems; dstItemIdx++)
 
            finalDest[dstItemIdx] =
                atomic_load_explicit(destMemory + dstItemIdx,
                                     memory_order_relaxed,
                                     memory_scope_work_group);
}
```

**Comment by bashbaug** [comment]
I agree this test case is invalid.  Since these are all relaxed atomics there are no memory consistency guarantees.  Good catch!

I _think_ the way to fix this is to make the `atomic_fetch_add_explicit` stronger, either via a different memory order on the atomic add itself (`memory_order_acq_rel` is sufficient?), or by adding fences around the atomic add.  This would probably need to be done at device scope, since we want consistency across the global range.  Does this sound correct?

**Comment by Jeremy-Kemp** [comment]
>I _think_ the way to fix this is to make the `atomic_fetch_add_explicit` stronger, either via a different memory order on the atomic add itself (memory_order_acq_rel is sufficient?)

We experimented with some different options internally, and this is the exact method we settled on as being the least impactful whilst also restoring the correctness of the test.

We have yet to assess whether the change effects any of the other suites (incorrectly) in c11_atomics as the change is to common code, but can put up a PR shortly for it.
