### ISSUE TITLE
in svm/test_shared_address_space_coarse_grain.cpp: allocator is created with sizeof(cl_int), but is mapped as size_t*

### ISSUE THREAD

**Issue by aharon-abramson** [KhronosGroup/OpenCL-CTS#1381]
In line 209 allocator is created as a buffer of sizeof(cl_int):
`clMemWrapper allocator = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(cl_int), NULL, &error);`

But in line 101 its mapped pointer is cast to size_t*:
`size_t*pAllocator = (size_t*)clEnqueueMapBuffer(cmdq, allocator, CL_TRUE, CL_MAP_READ | CL_MAP_WRITE, 0, sizeof(cl_int), 0, NULL,NULL, &error);`

And then pAllocator is referenced and assigned to:
`*pAllocator = numLists;`

**Comment by bashbaug** [comment]
Do we just need to allocate and map `sizeof(size_t)` or is more needed here?

**Comment by aharon-abramson** [comment]
No, that's it.
