### ISSUE TITLE
change allocation size from cl_int to size_t in the remaining SVM tests

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-CTS#1421]
#1381 describes a problem in the coarse grain SVM tests, but the same problem also seems to be in the fine-grain SVM tests also.  Note the mismatch between sizeof(cl_int) and size_t*.

```c
  // this allocation holds an index into the nodes buffer, it is used for node allocation
  size_t* pAllocator = (size_t*) align_malloc(sizeof(cl_int), 128);
```

**Comment by StuartDBrady** [comment]
Fixed by PR #1496.
