### ISSUE TITLE
currently not support the newly added format CL_ABGR?

### ISSUE THREAD

**Issue by stoneforestwhu** [KhronosGroup/OpenCL-CTS#1469]
after mesa2204 updated, the format CL_ABGR is not support yet. If following code is added in function read_image_pixel (imageHelpers.h), the test case for CL_ABGR will be passed.

` else if (format->image_channel_order == CL_ABGR)
    {
        outData[0] = tempData[3];
        outData[1] = tempData[2];
        outData[2] = tempData[1];
        outData[3] = tempData[0];
    }`

**Comment by bashbaug** [comment]
Hello!  This seems reasonable for me.  Would you mind making a PR with this addition?  Thanks!

**Comment by stoneforestwhu** [comment]
The PR has committed.  https://github.com/KhronosGroup/OpenCL-CTS/pull/1474,  please help to review, Thanks!
