### ISSUE TITLE
Test cl_khr_command_buffer_mutable_dispatch

### ISSUE THREAD

**Issue by EwanC** [KhronosGroup/OpenCL-CTS#1481]
Test plan for [cl_khr_command_buffer_mutable_dispatch](https://github.com/KhronosGroup/OpenCL-Docs/pull/819) breaking down the areas which need to be covered.

## 1 Device Info Query

Verify the following queries can be performed successfully and return
defined values:

- [x] `CL_DEVICE_MUTABLE_DISPATCH_CAPABILITIES_KHR`

EDIT - Done in https://github.com/KhronosGroup/OpenCL-CTS/pull/1651

### 2.1 Mutable-dispatch

For each property in `cl_mutable_dispatch_properties_khr` reported by device query.

* Create a command-buffer with `CL_COMMAND_BUFFER_MUTABLE_KHR`
* Record `clCommandNDRangeKernelKHR` returning a `cl_mutable_command_khr` object
* Enqueue command-buffer and verify
* Set a new value for the mutable value, and enqueue again, verify result
* Enqueue command-buffer again, without updating mutable-dispatch, and verify that new values have persisted.

- [x] `CL_MUTABLE_DISPATCH_GLOBAL_OFFSET_KHR` https://github.com/KhronosGroup/OpenCL-CTS/pull/1743
- [x] `CL_MUTABLE_DISPATCH_GLOBAL_SIZE_KHR` https://github.com/KhronosGroup/OpenCL-CTS/pull/1744
- [x] `CL_MUTABLE_DISPATCH_LOCAL_SIZE_KHR` https://github.com/KhronosGroup/OpenCL-CTS/pull/1745
- [x] `CL_MUTABLE_DISPATCH_ARGUMENTS_KHR` for normal arguments and SVM. Checking variants of:
  * __global arguments https://github.com/KhronosGroup/OpenCL-CTS/pull/1749
  * __local arguments https://github.com/KhronosGroup/OpenCL-CTS/pull/1749
  * POD (plain-old-data) arguments https://github.com/KhronosGroup/OpenCL-CTS/pull/1749
  * NULL arguments https://github.com/KhronosGroup/OpenCL-CTS/pull/1749
  * image arguments https://github.com/KhronosGroup/OpenCL-CTS/pull/1750
- [x] `CL_MUTABLE_DISPATCH_EXEC_INFO_KHR` Part of SVM test in https://github.com/KhronosGroup/OpenCL-CTS/pull/1749
- [x] Test modifying all supported mutable properties in each update https://github.com/KhronosGroup/OpenCL-CTS/pull/1905

#### 2.1.1 Multiple updates

- [x]  Test using `clUpdateMutableCommandsKHR()` in a way which updates more than one command-handle in the same call. https://github.com/KhronosGroup/OpenCL-CTS/pull/1919
- [x]  Test calling `clUpdateMutableCommandsKHR()` several times on the same command-handle and make sure that the most recent value persists. https://github.com/KhronosGroup/OpenCL-CTS/pull/1922
- [x] Test `clUpdateMutableCommandsKHR()`  being called multiple times on the same command before an enqueue, but with different arguments. Verify that all the combined updates are made correctly. https://github.com/KhronosGroup/OpenCL-CTS/pull/1925

### 2.1.2 Simultaneous use

- [x] single queue simultaneous-use https://github.com/KhronosGroup/OpenCL-CTS/pull/1746

> If a device supports simultaneous-use

* Test updating mutable-dispatch objects of a command-buffer while a previous instance of the command-buffer is in flight.

### 2.1.3 cross-queue simultaneous-use

- [x] cross-queue simultaneous-use

EDIT: https://github.com/KhronosGroup/OpenCL-CTS/pull/1912

> If a device supports simultaneous-use

Test updating mutable-dispatch objects of a command-buffer while a previous instance of the command-buffer is in flight to a different queue. See 1.3.3 from the [cl_khr_comand_buffer test plan](https://github.com/KhronosGroup/OpenCL-CTS/issues/1369), but changing one of the command-buffer enqueues to the original queue.

### 2.2 clGetMutableCommandInfoKHR

Test each of the queries in `clGetMutableCommandInfoKHR()`:

- [x] `CL_MUTABLE_COMMAND_COMMAND_QUEUE_KHR`
- [x] `CL_MUTABLE_COMMAND_COMMAND_BUFFER_KHR`
- [x] `CL_MUTABLE_DISPATCH_PROPERTIES_ARRAY_KHR`
- [x] `CL_MUTABLE_DISPATCH_KERNEL_KHR`
- [x] `CL_MUTABLE_DISPATCH_DIMENSIONS_KHR`
- [x] `CL_MUTABLE_DISPATCH_GLOBAL_WORK_OFFSET_KHR`
- [x] `CL_MUTABLE_DISPATCH_GLOBAL_WORK_SIZE_KHR`
- [x] `CL_MUTABLE_DISPATCH_LOCAL_WORK_SIZE_KHR`
- [x] `CL_MUTABLE_COMMAND_COMMAND_TYPE_KHR`

Edit - Done in https://github.com/KhronosGroup/OpenCL-CTS/pull/1651

**Comment by EwanC** [comment]
Noting that the mutable dispatch asserts from PR https://github.com/KhronosGroup/OpenCL-Docs/pull/992 also need CTS testing.

**Comment by shajder** [comment]
hello @EwanC, I am begining my work on finishing this issue and after initial review I am a bit concerned about points `2.1.2`/`2.1.3`. Work plan does not mention anything about out-of-order command queues, meanwhile there are already two (?) [tests added](https://github.com/KhronosGroup/OpenCL-CTS/pull/1746) addressing `2.1.2` which uses out-of-order queue, I am guessing inspired by `cl_khr_command_queue` preceding [tests](https://github.com/KhronosGroup/OpenCL-CTS/pull/1596). Do we want to leave it as is or get rid of out-of-order queues ? Do we want the new test addressing `2.1.3` to use out-of-order command queue ? Thanks

**Comment by EwanC** [comment]
Hi @shajder, that's great you are able to pick this up again. That's a good point about out-of-order queues, device support for that is conditional on `CL_COMMAND_BUFFER_CAPABILITY_OUT_OF_ORDER_KHR` but we still want to test devices which don't support that optional capability in the `2.1.2` / `2.1.3` scenarios. So could you add tests that only use in-order queues for these scenarios? Realize that doing `2.1.2` again for an in-order queue might involve some duplication of the original test unless it can be refactored to also support in-order.

Regarding getting rid of the out-of-order queues, using an out-of-order queue is a valid use of the extension so I'm a bit reluctant to reduce coverage from a valid test.

**Comment by shajder** [comment]
> ... So could you add tests that only use in-order queues for these scenarios? Realize that doing `2.1.2` again for an in-order queue might involve some duplication of the original test unless it can be refactored to also support in-order.

make sense, I will refactor code to handle all mentioned cases

> Regarding getting rid of the out-of-order queues, using an out-of-order queue is a valid use of the extension so I'm a bit reluctant to reduce coverage from a valid test.

understood, I will keep out-of-order test cases along with new in-order ones

**Comment by shajder** [comment]
@EwanC one more concern, in tests `mutable_dispatch_global_size`/`mutable_dispatch_local_size`/`mutable_dispatch_global_offset`  argument `cl_ndrange_kernel_command_properties_khr` is not passed to `clCommandNDRangeKernelKHR`. Is this a mistake? According to [spec](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_properties_parameter) (eg. `CL_MUTABLE_DISPATCH_GLOBAL_OFFSET_KHR`):

_... Determines whether the global_work_offset of kernel execution can be modified after recording. If set, the global_work_offset of the kernel execution can be changed with clUpdateMutableCommandsKHR using the cl_mutable_dispatch_config_khr field of the mutable_config parameter. **Otherwise, the global_work_offset cannot be modified**._

**Comment by EwanC** [comment]
> @EwanC one more concern, in tests `mutable_dispatch_global_size`/`mutable_dispatch_local_size`/`mutable_dispatch_global_offset` argument `cl_ndrange_kernel_command_properties_khr` is not passed to `clCommandNDRangeKernelKHR`. Is this a mistake? According to [spec](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_properties_parameter) (eg. `CL_MUTABLE_DISPATCH_GLOBAL_OFFSET_KHR`):
> 
> _... Determines whether the global_work_offset of kernel execution can be modified after recording. If set, the global_work_offset of the kernel execution can be changed with clUpdateMutableCommandsKHR using the cl_mutable_dispatch_config_khr field of the mutable_config parameter. **Otherwise, the global_work_offset cannot be modified**._

Another good question, there is the language in the spec for `cl_mutable_dispatch_fields_khr` that

> If CL_MUTABLE_DISPATCH_UPDATABLE_FIELDS_KHR is not specified then it defaults to the value returned by the CL_DEVICE_MUTABLE_DISPATCH_CAPABILITIES_KHR device query.

Therefore I think the tests are correct by that default wording since `CL_DEVICE_MUTABLE_DISPATCH_CAPABILITIES_KHR ` is checked in `Skip()`, however it does also leave a gap in testing about whether implementation correctly handle `cl_ndrange_kernel_command_properties_khr` if it is passed here. So I would say we could do something like improve the `mutable_dispatch_global_size`/`mutable_dispatch_local_size`/`mutable_dispatch_global_offset` tests to have a second run (or use a second kernel) where the `clCommandNDRangeKernelKHR` kernel is created with `cl_ndrange_kernel_command_properties_khr`

**Comment by shajder** [comment]
> Realize that doing `2.1.2` again for an in-order queue might involve some duplication of the original test unless it can be refactored to also support in-order.

Added #1912 along with two test cases:
-mutable dispatch with simultaneous use in in-order queue
-mutable dispatch with simultaneous use in cross queue scenario
