### ISSUE TITLE
verify argc allocation bugfix applicability to other tests

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-CTS#1509]
This PR fixed an out-of-bounds condition in test_half: https://github.com/KhronosGroup/OpenCL-CTS/pull/1489

There was some speculation that the same bug could have been copy-pasted into other tests.  We should check that other tests do not suffer from a similar problem.

Tagging @StuartDBrady since he may already be looking at this...

**Comment by niranjanjoshi121** [comment]
Found the same issue with test conversion here - 
https://github.com/KhronosGroup/OpenCL-CTS/blob/c014122742c211f8febb49324b9e99302e26018c/test_conformance/conversions/test_conversions.cpp#L346

Created PR #1513 to fix the same.

**Comment by pj87** [comment]
There have already been other fixes: https://github.com/KhronosGroup/OpenCL-CTS/pull/1513, https://github.com/KhronosGroup/OpenCL-CTS/issues/1376, https://github.com/KhronosGroup/OpenCL-CTS/pull/1489 and I have not seen any other occurences of the allocations that are affected with this OOB issue apart from the fixed ones.

**Comment by bashbaug** [comment]
Works for me, I'll close this issue and we can always reopen it (or file a new one) if we find additional issues.  Thanks!
