### ISSUE TITLE
Move existing cl_khr_semaphore tests from test_api into its own directory in test_conformance/extensions/

### ISSUE THREAD

**Issue by nikhiljnv** [KhronosGroup/OpenCL-CTS#1624]
Issue to track Ewan's request here to move cl_khr_semaphore tests from test_api into its own directory in test_conformance/extensions/
https://github.com/KhronosGroup/OpenCL-CTS/issues/1588#issuecomment-1340911465.

**Comment by nikhiljnv** [comment]
Mentioning #1646 which fixes this here for reference.

**Comment by kpet** [comment]
#1646 was merged, closing this issue.
