### ISSUE TITLE
Segfault when passing arguments to test_conformance_spirv_new

### ISSUE THREAD

**Issue by aarongreig** [KhronosGroup/OpenCL-CTS#167]
I am building cl21_trunk against the intel integrated graphics driver and when I run the spir-v tests with a filter (something like `op_undef*` for example) I get a segfault. Reproducing invocation and output:
```
./test_conformance_spirv_new -ILPath /home/aaron/proj/OpenCL-CTS/test_conformance/spirv_new/spirv_bin/ op_undef*
 Initializing random seed to 0.
Requesting Default device based on command line for platform index 0 and device index 0
Compute Device Name = Intel(R) Gen9 HD Graphics NEO, Compute Device Vendor = Intel(R) Corporation, Compute Device Version = OpenCL 2.1 NEO , CL C Version = OpenCL C 2.0 
Supports single precision denormals: YES
sizeof( void*) = 8  (host)
sizeof( void*) = 8  (device)
Segmentation fault (core dumped)
```
I think I have tracked the cause of this to [this line](https://github.com/KhronosGroup/OpenCL-CTS/blob/bffb24bf7156e591b578efa6aefc149e23dd9928/test_conformance/spirv_new/main.cpp#L167) in `test_conformance/spirv_new/main.cpp`, when I remove the `+1` on line 167 locally I can use test filtering with command line arguments as normal. This change also stops the `(null) test currently not implemented` output I see at the end of an unfiltered run. I am happy to open a PR for this as long as no one knows of any reason this might break something else.

**Comment by gwawiork** [comment]
My internal version of code do not have this + 1 in [this line](https://github.com/KhronosGroup/OpenCL-CTS/blob/bffb24bf7156e591b578efa6aefc149e23dd9928/test_conformance/spirv_new/main.cpp#L167) I will check other differences too and pushed out fix. Please remove "+1" and verify if then works for you

**Comment by aarongreig** [comment]
I can confirm that removing +1 fixes the issue

**Comment by kpet** [comment]
PR merged, closing.
