### ISSUE TITLE
cl_khr_command_buffer::info_state does not check the state after the command buffer has completed execution

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#1690]
Once a command buffer completes execution (assuming no other pending instances), its state should be transitioned back to `CL_COMMAND_BUFFER_STATE_EXECUTABLE_KHR`. The info_state test should check that.

**Comment by pj87** [comment]
There is already state verification for `RunStateInfoTests()`:

```
error = verify_state(CL_COMMAND_BUFFER_STATE_EXECUTABLE_KHR);
test_error(error, "verify_state failed");
```

Could you please specify the details of the requirements for the tests? What other tests should be extended here?

**Comment by shajder** [comment]
@kpet at the moment such a scenario is tested in [CommandBufferGetCommandBufferInfo::RunStateInfoTest](https://github.com/KhronosGroup/OpenCL-CTS/blob/da4a30d394c04667178d74902092d2120963c863/test_conformance/extensions/cl_khr_command_buffer/command_buffer_get_command_buffer_info.cpp#L268-L269), I think we can close that issue.

**Comment by kpet** [comment]
It looks like this was fixed by https://github.com/KhronosGroup/OpenCL-CTS/pull/1740 but the issue was never closed. Closing now.
