### ISSUE TITLE
A few missing cl_khr_semaphore tests

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#1691]
- [ ] `CL_DEVICE_HANDLE_LIST_KHR` as a query using `clGetSemaphoreInfoKHR`
- [ ] `CL_DEVICE_HANDLE_LIST_KHR` as a property passed to `clCreateSemaphoreWithPropertiesKHR`
- [ ] Negative tests for the API error codes of
  - [ ] `clCreateSemaphoreWithPropertiesKHR`
  - [ ] `clEnqueueWaitSemaphoresKHR`
  - [ ] `clEnqueueSignalSemaphoresKHR`
  - [ ] `clGetSemaphoreInfoKHR`
  - [ ] `clReleaseSemaphoreKHR`
  - [ ] `clRetainSemaphoreKHR`

Note that `CL_DEVICE_HANDLE_LIST_KHR` may be renamed depending on what https://github.com/KhronosGroup/OpenCL-Docs/issues/864 concludes.

**Comment by nikhiljnv** [comment]
Have filed https://github.com/KhronosGroup/OpenCL-CTS/issues/1875 for CL_DEVICE_HANDLE_LIST_KHR coverage.
