### ISSUE TITLE
Command buffer re-enqueue testing

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#1693]
We should have tests checking that command buffers can be enqueued again after having completed execution.

**Comment by bashbaug** [comment]
Basic idea for this test, as I understand:

1. Create a command buffer that modifies some buffer `B`.
2. Execute the command buffer the first time.
3. Wait for execution to complete.  Check that the buffer `B` was properly modified.

(note: most command buffer testing so far has done these steps.)

4. Write data to the buffer `B` to re-initialize it.
5. Execute the same command buffer again, a second time.  Note, use the same command buffer, do NOT recreate it!.
6. Wait for execution to complete.  Check that the buffer `B` was properly modified, again.

Minimum would be to do this test for just one type of command in a command buffer to ensure basic replay works.  Better would be to test more (all?) types of commands in a command buffer.

@kpet feel free to add any additional detail or things I may have missed.

**Comment by kpet** [comment]
That's exactly what I had in mind. Thanks for writing this up, I'll cross that off my to-do list :).

**Comment by pj87** [comment]
Should it be done for any specific set of tests or maybe all of them where it is applicable?

**Comment by shajder** [comment]
> Possibly already covered by #1738?

I just went through #1738, looks to me like initially there was separate `BasicReenqueueTest` but later re-enqueue scenario was implemented in other tests eg. `BasicEnqueueTest`. @EwanC can we close this one ?

**Comment by EwanC** [comment]
Yes, I think this gap is covered by #1738 so i'll close this
