### ISSUE TITLE
Undefined behaviour in conversions tests

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/OpenCL-CTS#1784]
#1719 updated the conversions tests. Unfortunately, it includes undefined behaviour for several cases.

C++17 reference spec: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4640.pdf
>2 A prvalue of an integer type or of an unscoped enumeration type can be converted to a prvalue of a floatingpoint type. The result is exact if possible. If the value being converted is in the range of values that can
be represented but the value cannot be represented exactly, it is an implementation-defined choice of either
the next lower or higher representable value. [ Note: Loss of precision occurs if the integral value cannot
be represented exactly as a value of the floating type. — end note ] If the value being converted is outside
the range of values that can be represented, the behavior is undefined. If the source type is bool, the value
false is converted to zero and the value true is converted to one.

From 4.10 floating-integral conversions  [conf.fpint]
>A prvalue of a floating-point type can be converted to a prvalue of an integer type. The conversion truncates;
that is, the fractional part is discarded. The behavior is undefined if the truncated value cannot be represented
in the destination type. [ Note: If the destination type is bool, see 4.14. — end note ]

The data setup for the conversion tests attempt to get some ranges in the `DataInfoSpec` constructor.  The code looks like the following (approximately):
```
if (out_type == cl_float) {
  range = std::make_pair(CL_FLT_MIN, CL_FLT_MAX);
} else if (...) {
  // other type cases
}

InType outMin = (InType)range.first;
InType outMax = (InType)range.second;
```

For conversion to float from integers this ends up trying to convert CL_FLT_MAX to an integer. C++ says this is UB. On our internal test runners this is causing a crash.

**Comment by svenvh** [comment]
@alan-baker thanks for the report.  I couldn't produce a crash myself for this UB, but I agree with your analysis.

Would you be able to confirm if #1786 fixes the issue on your side?

**Comment by alan-baker** [comment]
I'll test it out.

**Comment by alan-baker** [comment]
The crashes are gone, but I'm seeing failures on multiple devices (GPU and CPU) for `convert_float_rtn(uint)`
```
Error for vector size 1 found at 0x00000000:  *-0x0p+0 vs 0x0p+0
Input value: 0x00000000  (convert_float_rtn( uint ))
```
This only happens in optimized builds for me.  Debug builds are correct. The reference is calculating a negative 0 for an exact representation of an unsigned integer 0. That seems odd.

Your fix is likely ok, but there seems to be a lingering issue that needs investigated.

**Comment by svenvh** [comment]
@alan-baker thanks for testing.

I have pushed another commit to #1786 that should hopefully resolve the negative-0 issue.  Would you be able to test the latest version of that PR?

**Comment by alan-baker** [comment]
> @alan-baker thanks for testing.
> 
> I have pushed another commit to #1786 that should hopefully resolve the negative-0 issue. Would you be able to test the latest version of that PR?

I just tested this out and everything is green. Thanks for digging into it for me!
