### ISSUE TITLE
Random failure for Basic/imagedim_non_pow2 test case on Windows 32bit

### ISSUE THREAD

**Issue by cdai2** [KhronosGroup/OpenCL-CTS#1842]
OS cannot allocate a contiguous memory space (~256MB) when the test tried to create large 2D images intensively (the free virtual memory is running low, ~300MB available, however, might be fragmented). 

Because the 32 bit test executable is not linked with "LARGEADDRESSAWARE" so only 2GB virtual memory address space is available for the test – which might not be sufficient. If this "LARGEADDRESSAWARE" link option is used, test case passes.

**Comment by bashbaug** [comment]
I haven't run into this personally but it sounds like something that could certainly happen.

Is the fix to just set LARGEADDRESSAWARE for 32-bit MSVC builds?

Something like:

```cmake
if(MSVC AND ${CLConform_TARGET_ARCH} STREQUAL "x86")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS } /LARGEADDRESSAWARE")
endif()
```

**Comment by cdai2** [comment]
> I haven't run into this personally but it sounds like something that could certainly happen.
> 
> Is the fix to just set LARGEADDRESSAWARE for 32-bit MSVC builds?
> 
> Something like:
> 
> ```cmake
> if(MSVC AND ${CLConform_TARGET_ARCH} STREQUAL "x86")
>     set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS } /LARGEADDRESSAWARE")
> endif()
> ```

Yes, the fix is setting LARGEADDRESSAWARE for 32-bit build. 
we will land a PR to fix it.

**Comment by Nuullll** [comment]
#1858 for this.
