### ISSUE TITLE
test plan for CL_MUTABLE_DISPATCH_ASSERT_NO_ADDITIONAL_WORK_GROUPS_KHR

### ISSUE THREAD

**Issue by aharon-abramson** [KhronosGroup/OpenCL-CTS#1897]
The `CL_MUTABLE_DISPATCH_ASSERT_NO_ADDITIONAL_WORK_GROUPS_KHR` is, as its name suggests, an assertion from the user to the OpenCL runtime. It promises that for a command buffer or some of its ND-range kernel commands, if the user explicitly sets the number of workgroups (by specifying a non-null local work size) to be WG<sub>0</sub> when the ND-range kernel command is recorded, the new number of workgroups - if updated - WG<sub>u</sub>, will not be greater than WG<sub>0</sub>. 

The runtime may use this assertion to choose an implementation optimized for this maximum number of workgroups, or it may choose to ignore it. In any case, this decision should not affect the results of the kernel.

The test items described below shall be run in three configurations:
 - The command buffer is created with `CL_MUTABLE_DISPATCH_ASSERT_NO_ADDITIONAL_WORK_GROUPS_KHR` in its properties.
 - The ND-range command is recorded with `CL_MUTABLE_DISPATCH_ASSERT_NO_ADDITIONAL_WORK_GROUPS_KHR` in its properties.
 - Both the command buffer and ND-range command have `CL_MUTABLE_DISPATCH_ASSERT_NO_ADDITIONAL_WORK_GROUPS_KHR` in their properties.

The test items will follow the same template:
 1. Create a kernel that does some computation and writes the number of its workgroups into an output buffer.
 2. Create the necessary buffers.
 3. Set the kernel's arguments.
 4. Create a command buffer.
 5. Record an ND-range kernel of the kernel above in the command buffer with a non-null local work size so that the resulting number of workgroups will be greater than 1.
 6. Finalize the command buffer.
 7. Enqueue the command buffer.
 8. Wait for the command buffer's completion.
 9. Validate the kernel's results and expected number of workgroups.
 10. Update the command buffer according to the test items in the table below.
 11. Enqueue the command buffer.
 12. Wait for the command buffer's completion.
 13. Validate the kernel's results and the expected number of workgroups.

| Test items | Pass/Fail criteria |
|------------|--------------------|
| WG<sub>u</sub> = WG<sub>0</sub> | Kernel results are valid. Kernel's number of workgroups is WG<sub>u</sub>. |
| WG<sub>u</sub> < WG<sub>0</sub> | Kernel results are valid. Kernel's number of workgroups is WG<sub>u</sub>. |
| Call `clUpdateMutableCommandsKHR` to update the number of workgroups to WG<sub>1</sub>, which is less than WG<sub>0</sub>. Then, call the API function again to update the number of workgroups to be WG<sub>u</sub> so that WG<sub>0</sub> ≥ WG<sub>u</sub> > WG<sub>1</sub>. | Kernel results are valid. Kernel's number of workgroups is WG<sub>u</sub>. |

Since we have decided not to validate the assertion in `clUpdateMutableCommandsKHR` for performance reasons, the test plan does not include negative tests.

**Comment by EwanC** [comment]
Question about the table item:

> Call clUpdateMutableCommandsKHR with local_work_size set to NULL.

NULL represents no change to the work size, I don't think we can replicate the semantics of initially creating the kernel command with a NULL local size as things are currently specified.

From the description of this struct member in https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_mutable_command_types

> local_work_size Points to an array of work_dim unsigned values that describe the number of work-items that make up a work-group that will execute the kernel. If local_work_size is NULL then the number of local work-items in the dispatch is not changed

**Comment by aharon-abramson** [comment]
thanks!

**Comment by EwanC** [comment]
@aharon-abramson Okay to close this now that https://github.com/KhronosGroup/OpenCL-CTS/pull/1991 is merged

**Comment by aharon-abramson** [comment]
[like]  Aharon Abramson reacted to your message:
________________________________
