### ISSUE TITLE
CL_DEVICE_WORK_GROUP_COLLECTIVE_FUNCTIONS_SUPPORT not needed for `work_group_suggested_local_size_{1,2,3}D`

### ISSUE THREAD

**Issue by dtobolik** [KhronosGroup/OpenCL-CTS#1908]
Currently followining tests require `CL_DEVICE_WORK_GROUP_COLLECTIVE_FUNCTIONS_SUPPORT`
```
work_group_suggested_local_size_1D
work_group_suggested_local_size_2D
work_group_suggested_local_size_3D
```
I [implemented](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28020) `cl_khr_suggested_local_work_size` and the mentioned  tests pass if I enable `CL_DEVICE_WORK_GROUP_COLLECTIVE_FUNCTIONS_SUPPORT`, but it shouldn't be needed.

**Comment by bashbaug** [comment]
IMHO these tests should move to a different suite, perhaps test_api.

**Comment by karolherbst** [comment]
@bashbaug was it already decided that mobica will work on this, because I was also discussing this with @dtobolik, so we should probably coordinate here who is going to work on this.

**Comment by bashbaug** [comment]
> we should probably coordinate here who is going to work on this.

The "triage" issues aren't assigned yet, so they're fair game.  The ones to stay away from (or at least, to coordinate tightly) are the "backlog" issues.  Should be all good here though - thanks!
