### ISSUE TITLE
gl case double glutInit issue 

### ISSUE THREAD

**Issue by energystoryhhl** [KhronosGroup/OpenCL-CTS#2012]
I found an issue about CTS running  gl / CL-GL interop case issue, I found glutInit double called in CTS CLGL test case code, which will lead to an error:

                freeglut (./test_gl): illegal glutInit() reinitialization attempt

root cause is in: test_conformance/gl/main.cpp:343

                if (glEnv->Init(&argc, (char **)argv, CL_TRUE))

the glEnv->Init has already called in same file line:260, the function glutInit in glEnv->Init can not be called twice, then a error will occur although all the gl / CLGL cases are passed. Then in the full quick CTS running it will appear:

                (12-Jul 03:54:01)     BEGIN  OpenCL-GL Sharing                       : 
               PASSED sub-test.
               PASSED 23 of 23 tests.
               (12-Jul 04:01:48)     FAILED OpenCL-GL Sharing                       : (467s, test  34/53)

Although all the gl/CLGL cases are passed, but this group test is judged to failed.  Can you please help to take a look?

**Comment by bashbaug** [comment]
Probably related to https://github.com/KhronosGroup/OpenCL-CTS/pull/1885?

**Comment by energystoryhhl** [comment]
> Probably related to #1885?

I found this issue has been solved:
https://github.com/KhronosGroup/OpenCL-CTS/commit/02471c8f56d75ef8e46c20a3dd00503faddf7a4e

**Comment by energystoryhhl** [comment]
@bashbaug  I created a PR:https://github.com/KhronosGroup/OpenCL-CTS/pull/2023 to fix gluinit issue in osx, can you please help to review? Can you please help to review it?

**Comment by energystoryhhl** [comment]
https://github.com/KhronosGroup/OpenCL-CTS/pull/2023 fixed osx gl double init issue.
