### ISSUE TITLE
printf is incorrectly testing vector arguments 

### ISSUE THREAD

**Issue by coldav** [KhronosGroup/OpenCL-CTS#2039]
https://github.com/KhronosGroup/OpenCL-CTS/pull/2019 added multiple vector tests including:

float3 tmp = (float3)(1234.25f,987654.5f,0.0005f);   printf("%.2v3e\n",tmp);}

This does not include a length specifier. The spec says that "If a vector specifier appears without a length modifier, the behaviour is undefined. "

There are a few others like this.

**Comment by bashbaug** [comment]
Should we revert #2019 while we get this worked out?  CC @shajder

**Comment by shajder** [comment]
> Alternatively (to a revert), I think this should fix the vector test too: #2044

@svenvh is there anything more to do around this issue ?

**Comment by svenvh** [comment]
If #2044 gets merged I believe we can close this issue.
