### ISSUE TITLE
Handling of in-tree SPIR-V assembly/binaries

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#21]
A few issues to discuss:
* Do we really want to commit the binaries? Shouldn't we just generate them from the assembly as part of the build system?
* The assembly doesn't use the same syntax as the SPIR-V disassembler which makes it hard to check consistency between the binaries and assembly or check that PRs modify the binaries and assembly in the same manner.

**Comment by StuartDBrady** [comment]
The assembly source for the tests was updated to match the disassembler output after reassembling in PR #472. (The directory for the assembly source was also renamed from "spirv_txt" to "spirv_asm" in this PR.)

This leaves the matter of removing the binaries. A dependency on the SPIR-V Tools would seem potentially onerous for any implementation that does not require SPIR-V. My recommendation is that we add a script for assemble the SPIR-V assembly into binaries (and running spirv-val on them). This script would need to be run as a preparatory step, prior to running the spirv_new test.
