### ISSUE TITLE
Re-enable or delete dead code in test_external_semaphore.cpp

### ISSUE THREAD

**Issue by shajder** [KhronosGroup/OpenCL-CTS#2109]
While working on issue #1989 I've noticed in `test_external_semaphore.cpp` there is a function named `test_external_semaphores_simple_2` which is not scheduled for test. Should this be removed or re-enabled?

**Comment by joshqti** [comment]
After reviewing and testing, I don't see any harm in enabling it.  I have pushed a PR to enable it and delete some other dead code.

https://github.com/KhronosGroup/OpenCL-CTS/pull/2123

**Comment by nikhiljnv** [comment]
Now that https://github.com/KhronosGroup/OpenCL-CTS/pull/2123 is merged, can we close this? Or is there more work left here?

**Comment by shajder** [comment]
@nikhiljnv I think that's it, closing!
