### ISSUE TITLE
cl12 Document and check custom CMake variables

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/OpenCL-CTS#220]
1. If one clones the repository and tries to run
    ```
    mkdir build && cd build
    cmake ..
    ```
    one is greeted with the following error messages
    ```
    CMake Error at spir/CMakeLists.txt:2 (install):
      install FILES given no DESTINATION!
    Call Stack (most recent call first):
      spir/CMakeLists.txt:69 (install_spir_artifacts)


    CMake Error at spir/CMakeLists.txt:2 (install):
      install FILES given no DESTINATION!
    Call Stack (most recent call first):
      spir/CMakeLists.txt:70 (install_spir_artifacts)
    
    …
    ```
    due to not having set `CLConf_OUT_DIR`. But how should one know about it as it is not mentioned in the main CMakeLists.txt file nor in the README.md.
    
    The main CMakeLists.txt should at least check for that value being defined, and if not emit an error informing the user to set it. I guess it could also be automatically set to `CMAKE_BINARY_DIR` if unset.

2. `CLConform_LIB_DIR`, `CLConform_LIBRARIES` and `CLConform_HEADERS` also need to be documented somewhere.

**Comment by EwanC** [comment]
After https://github.com/KhronosGroup/OpenCL-CTS/pull/1427 we should now document all the custom CMake variables needed for a build, which is now `CL_INCLUDE_DIR`, `CL_LIB_DIR`, and `OPENCL_LIBRARIES` . I think this is enough information to close this issue.

**Comment by pierremoreau** [comment]
Indeed, thank you for updating the README file!
