### ISSUE TITLE
cl12: Compiling with Clang-8 requires -Wno-c++11-narrowing

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-CTS#222]
Currently compiling the `cl12_trunk` branch with recent versions of Clang requires the `-Wno-c++11-narrowing` flag, effectively due to the way older C code and C++ code are mixed.   However, the CMake does not set this itself.

Locally when we import the CTS into our project we have something like this in our own CMake:

```
  if(CMAKE_CXX_COMPILER_ID STREQUAL Clang OR
      CMAKE_CXX_COMPILER_ID STREQUAL AppleClang)
    string(APPEND CMAKE_CXX_FLAGS " -Wno-c++11-narrowing")
  endif()
```

**Comment by kpet** [comment]
I have to pass this flag as well in my clvk build environment. The number of code changes required is quite large so I suggest we defer them until we have a single branch. In the meantime we probably should define the warning suppression flag to toolchains that support it.

**Comment by alycm** [comment]
Agreed, my intent was to suppress the warnings for now.

**Comment by pierremoreau** [comment]
This could be closed now (somehow it wasn’t closed when the MR was merged), unless you want to repurpose it for the gcc situation?
