### ISSUE TITLE
cl12 cl20 cl21 cl22: Integer overflow in allocations tests with 32-bit size_t

### ISSUE THREAD

**Issue by StuartDBrady** [KhronosGroup/OpenCL-CTS#231]
The `find_good_image_size()` function in `test_conformance/allocations/allocation_functions.cpp` has an integer overflow bug, in that if the product of `max_height` and `max_width` is too large for a `size_t`, the function will fail.

**Comment by kpet** [comment]
Fixed by https://github.com/KhronosGroup/OpenCL-CTS/pull/610
