### ISSUE TITLE
cl12 cl20 cl21 cl22 bruteforce macro_unary float tests can't fail

### ISSUE THREAD

**Issue by jlewis-austin** [KhronosGroup/OpenCL-CTS#249]
(migrated from gitlab)
The TestFloat() function in macro_unary.c has an exit block that overwrites any incoming errors. Failing test cases will be logged but the overall test reports PASSED if the cleanup code completes without error. Test cases affected: isfinite, isinf, isnan, isnormal, signbit, not

**Comment by kpet** [comment]
Fixed on all branches, closing.
