### ISSUE TITLE
Travis configuration files need to be updated after changes in OCL IcdLoader project

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#264]
I see changes in ICD loader project introducted by commit https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/7d2584c4b8b1ac186f67143aaa2f846184709a9e

I think without this changes in travis configuration build will fails.

**Comment by kpet** [comment]
All PRs merged. Closing.
