### ISSUE TITLE
cl12 cl20 cl21 cl22 image_streams write tests pass with up to 5 errors per image

### ISSUE THREAD

**Issue by jlewis-austin** [KhronosGroup/OpenCL-CTS#27]
All the test_write_image_* functions declare int totalErrors=0 as the first line, then redeclare it in the main for loop. The outer variable is returned at the end and is always 0.

The only way to fail the test is by early exit; e.g. finding numTries (5) failures in a single image.

**Comment by kpet** [comment]
Fixed on all branches, closing! Thanks!
