### ISSUE TITLE
clcpp cases - current test case registration code have undefined behavior

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#278]
It looks that current registration methods for test cases in clcpp/ directory is incorrect. I compiled them using MSVC and was observing that test case names (test_case.exe -list) displayed some random unicode characters instead of test_names. Example:
8.■≈
8.■≈
test_spec_constants_initializing_variables
The problem is in the line:
::autotest::test_suite::global_test_suite().add(test_definition({ptr, name.c_str()}))
name - is the temporary variable which after exit function is not accessible.

**Comment by kpet** [comment]
PR merged, closing.

It would be great if you could use one of the keywords that closes issues automatically for similar cases (see https://help.github.com/en/articles/closing-issues-using-keywords).
