### ISSUE TITLE
cl12 cl20 cl21 cl22 image_streams write tests don't allow flushing float denormals

### ISSUE THREAD

**Issue by jlewis-austin** [KhronosGroup/OpenCL-CTS#28]
The write tests use a normalized error fabsf( ( expected[ j ] - actual[ j ] ) / expected[ j ] ) for non-zero expected results. For denormals that get flushed to zero, this will compute a failing error value (e.g. 1 for CL_R images). 

Additional issues in the error computation (limited here to CL_FLOAT tests in test_write_image_1D()):

1. CL_FLOAT images are tested against a relative error of 0.005f, which has no correlation to spec requirements. 
2. The computed "err" is averaged over all channels, which is not provide for in the spec
3. NaN/Inf are not considered in the relative error calculation, and can lead to both false fails and false passes.

The overall test can still pass due to #27

**Comment by jlewis-austin** [comment]
Per discussion with @kpet, this fix is not trivially portable to cl12_trunk, so will leave this open until 1.2 is validated in master branch.

**Comment by kpet** [comment]
@jlewis-austin Can this be closed now?

**Comment by jlewis-austin** [comment]
@kpet yes thanks
