### ISSUE TITLE
The value returned by CL_DEVICE_IL_VERSION isn't validated

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#293]
The CTS should validate:
* the format of entries
* the presence of SPIR-V and the presence of required versions

**Comment by gwawiork** [comment]
This is covered by https://github.com/KhronosGroup/OpenCL-CTS/pull/717 (at least partially)

**Comment by ellnor01** [comment]
I believe that #717 covers the second bullet point. 
The format of entries is validated under the extending_versioning test from #548: https://github.com/KhronosGroup/OpenCL-CTS/blob/6adf4ead5cc39f405568ff4f30095dcccaecd9a4/test_conformance/computeinfo/extended_versioning.cpp#L480
