### ISSUE TITLE
Test SVM gap - test clEnqueueSVMMemcpy in case of host memory allocation

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#299]
The test test_enqueue_api checks if API function clEnqueueSVMMemcpy works when both (source and destination) memory pointers are SVM allocations. We should check also case when one of the allocation (source or destination) is a host memory. The discussion about this topic inside the Khronos group was [here](https://www.khronos.org/members/login/bugzilla/show_bug.cgi?id=14598)
My proposal it to extend the existing test case equeue_api to test host memory as a source or destination memory.

**Comment by kpet** [comment]
Fixed on all relevant branches. Closing.
