### ISSUE TITLE
Several tests aren't meaningful in SPIR-V mode (2.1)

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#31]
They use online compilation and completely bypass the SPIR-V offline path. A few examples:
* `basic/int*`
* `basic/createkernelsinprogram`
* `api/null_buffer_arg`
* `api/kernels`
* `api/create_kernels`
* `generic_address_space/advanced_tests`
* ...

**Comment by boazo** [comment]
Could you elaborate what you mean that the test completely bypasses the SPIR-V offline path?

**Comment by kpet** [comment]
Yes, apologies, the issue could have been clearer. Some tests (see `test_conformance/contractions/contractions.c` for an example) are using  `clCreateProgramWithSource`, `clBuildProgram`, etc instead of calling the `create_single_kernel_helper*` functions provided by the framework. These tests need to be converted to use the framework functions if we want the offline flow to work. Note that in some cases, it might make sense for tests not to use the framework functions (thinking of tests in `test_conformance/compiler/` for example).

**Comment by ellnor01** [comment]
Working on this. 
Work done in #840 contributes to this. Some remaining unnecessary uses of clCreateProgramWithSource are highlighted under #1049
I am currently working on using the helper functions where possible for clBuildProgram and clCreateKernel
