### ISSUE TITLE
Exit codes potentially bogus

### ISSUE THREAD

**Issue by mantognini** [KhronosGroup/OpenCL-CTS#32]
It appears that many `main` functions return the result from `runTestHarness` directly. https://github.com/KhronosGroup/OpenCL-CTS/search?q=runTestHarness&unscoped_q=runTestHarness

While not being documented, `runTestHarness` returns the number of failed tests. This number is not constraint to a specific domain (e.g. `[0, 255[`).

Because this number is returned from `main` functions, this leads to undefined behaviour when this number is outside the domain specified by the C or C++ standard. In practice, this means that returning values bigger than 256 on some Linux machine could be truncated to 0 and therefore lead the test infrastructure to think everything went okay.

Instead, to avoid any undefined behaviour, the main function should probably return either `EXIT_SUCCESS` or `EXIT_FAILURE` to err on the side of caution.

**Comment by kpet** [comment]
Looking at the code again, you are right, the return code issue on the binary itself (our use of JSON reports is what confused me) is still present and still very much needs fixing.

**Comment by mantognini** [comment]
Created #296, #297 and #298.

**Comment by kpet** [comment]
All PRs merged, closing.
