### ISSUE TITLE
Truncated output log file in case of printing output with stdout redirection to file

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#337]
I noticed such issue on latest version of Windows 10 then I propose turn off stdout buffering in test_harness function parseAndCallCommandLineTests
example:
test_conformance_basic.exe if > testlog.txt 

then testlog.txt content can be:

Requesting Default device based on command line for platform index 0 and device index 0
Compute Device Name = Intel(R) UHD Graphics 630, Compute Device Vendor = Intel(R) Corporation, Compute Device Version = OpenCL 2.1 NEO , CL C Version = OpenCL C 2.0 
Supports single precision denormals: YES
sizeof( void*) = 8  (host)
sizeof( void*) = 8  (device)
if...

**Comment by kpet** [comment]
Have you observed this issue only on Windows? Does it happen even when the test completes successfully? Have you considered calling fflush(stdout) before exiting instead of turning off buffering?

**Comment by gwawiork** [comment]
Yes only Windows. Please hold on with merging this. Maybe this is OS issue. I will inform later

**Comment by kpet** [comment]
Closing in accordance with https://github.com/KhronosGroup/OpenCL-CTS/pull/339#issuecomment-515452472.
