### ISSUE TITLE
cl12 and cl20 test_half uses long data type without checking for embedded profile devices

### ISSUE THREAD

**Issue by lpavank** [KhronosGroup/OpenCL-CTS#344]
test_half, in cl_utils.c, uses 'long' data types as a way to enforce certain alignments.  For this test 'long' can simply be replaced with 'int2' with no other changes to the test are needed.  This is already fixed in the 2.1+ test branches.

**Comment by kpet** [comment]
This has been fixed on the master branch which can now be used to test 1.x implementations. Closing.
