### ISSUE TITLE
cl12 cl20 cl21 image_helpers missing break in switch statement, causing special float number generation to be skipped

### ISSUE THREAD

**Issue by lpavank** [KhronosGroup/OpenCL-CTS#346]
I think there is a missing break in the switch statement that generates the float inputs for the image tests.  The missing break causes our floating point numbers to be overwritten with integers.
cl12_trunk:  test_conformance\images\image_helpers.cpp line 2753
               default:
                    size_t i = 0;
                    if( numPixels * 4 >= 36 )
                    {
                        inputValues[ i++ ] = 0.0f;
                        inputValues[ i++ ] = 0.5f;
                        inputValues[ i++ ] = 31.5f;
                        inputValues[ i++ ] = 32.0f;
// --- snip  other float generation-----                       

                    }
                    if( is_format_signed(imageInfo->format) )
                    {
                        for( ; i < numPixels * 4; i++ )
                            inputValues[ i ] = get_random_float( -1.1f, 1.1f, d );
                    }
                    else
                    {
                        for( ; i < numPixels * 4; i++ )
                            inputValues[ i ] = get_random_float( -0.1f, 1.1f, d );
                    }
                    break;
            }
// break; should be here? - else fall through to kInt case
        }
            
        case kInt:
        {
            int *imageData = (int *)data;
            
cl21_trunk: test_common/harness/imageHelpers.cpp line 3314, same as above

**Comment by kpet** [comment]
Fixed on all branches, closing.
