### ISSUE TITLE
cl12 Image streams - issues in low memory environment

### ISSUE THREAD

**Issue by lpavank** [KhronosGroup/OpenCL-CTS#347]
The fix for Bugzilla 13546 (https://www.khronos.org/members/login/bugzilla/show_bug.cgi?id=13546):

Image streams max_images test can allocate an input buffer which exceeds a max allocation size reported by an implementation. The test estimates a max size of allocations based on an image type, number of channels and channel data type.

...was never committed to the 1.2 CTS branch port if needed, only 2.0+.

**Comment by jlewis-austin** [comment]
This can be closed; verified the patch is in the master branch now.

**Comment by kpet** [comment]
Thanks for checking! Closing.
