### ISSUE TITLE
cl12 cl20 cl21 cl22 - User defined size while querying clGetDeviceInfo and CL_DEVICE_EXTENSIONS

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#35]
This can generate test errors when extension string is bigger than test expects (then CL_INVALID_VALUE will be returned). 
The following tests will be affected:
- all spir tests 
`char extensions[1024] = {0};
    size_t size;
    // Querying the device for its supported extensions
    cl_int errcode = clGetDeviceInfo(devId,
                                     CL_DEVICE_EXTENSIONS,
                                     sizeof(extensions),
                                     extensions,
                                     &size);`
- computeinfo
For example computeinfo tests defines config_data union where one of the filed is :
`char                            string[1024];`

**Comment by alycm** [comment]
There are PRs open for OpenCL 2.0/2.1/2.2.  Is the patch expected to apply to OpenCL 1.2 as well?

**Comment by kpet** [comment]
All PRs merged, closing.

**Comment by kpet** [comment]
Note: this hasn't been fixed on cl12_trunk.
