### ISSUE TITLE
The value returned for CL_DEVICE_OPENCL_C_VERSION isn't validated

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#364]

**Comment by kpet** [comment]
Likely to get done as part of #897

**Comment by neiltrevett** [comment]
364 897 899 – should be looked at together

**Comment by bashbaug** [comment]
Is this entirely a duplicate of #897 and #899 or is there something specific for it?

I'll note that the format of the string returned by `CL_DEVICE_OPENCL_C_VERSION` is validated by `test_api min_max_language_version`.  We do need to add tests to ensure the values returned are meaningful though, but I believe this is captured in #897 and #899.

If there is no specific action required for this issue then I think we should close it.

**Comment by bashbaug** [comment]
Closing this issue.  If any additional checks are needed please include them in the review of PR #968.  Thanks!
