### ISSUE TITLE
Test computeinfo should know each existing OCL version

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#365]
The current implementation computeinfo test will fail in the following cases:

- binary from cl20 branch running on OCL2.1 platfrom, all devices OCL2.1 - “unexpected version string”
- binary from cl20 branch running on OCL2.1 platform,  all devices OCL2.1 excluding one which supports OCL2.0 - “unexpected version string”

The computeinfo test from each branch version should know each OCL string version.

**Comment by gwawiork** [comment]
Notice cl12_trunk branch - computeinfo test has different code than in other branches. So fix is here not applicable

**Comment by kpet** [comment]
All PRs merged, closing.
