### ISSUE TITLE
cl21: test_basie/progvar fails for 64bit atomic types

### ISSUE THREAD

**Issue by hewj03** [KhronosGroup/OpenCL-CTS#369]
error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_base_atomics extension to be enabled
error: use of type 'atomic_ulong' (aka '_Atomic(unsigned long)') requires cl_khr_int64_base_atomics extension to be enabled
error: use of type 'atomic_double' (aka '_Atomic(double)') requires cl_khr_int64_base_atomics extension to be enabled
error: use of type 'atomic_intptr_t' (aka '_Atomic(long)') requires cl_khr_int64_base_atomics extension to be enabled
error: use of type 'atomic_uintptr_t' (aka '_Atomic(unsigned long)') requires cl_khr_int64_base_atomics extension to be enabled
error: use of type 'atomic_size_t' (aka '_Atomic(unsigned long)') requires cl_khr_int64_base_atomics extension to be enabled
error: use of type 'atomic_ptrdiff_t' (aka '_Atomic(long)') requires cl_khr_int64_base_atomics extension to be enabled

**Comment by hewj03** [comment]
CL 2.0 spec:
[45] The atomic_long and atomic_ulong types are supported if the cl_khr_int64_base_atomics and
cl_khr_int64_extended_atomics extensions are supported and have been enabled.
[46] The atomic_double type is only supported if double precision is supported and the
cl_khr_int64_base_atomics and cl_khr_int64_extended_atomics extensions are supported and
have been enabled.
[47] If the device address space is 64-bits, the data types atomic_intptr_t, atomic_uintptr_t,
atomic_size_t and atomic_ptrdiff_t are supported if the cl_khr_int64_base_atomics and
cl_khr_int64_extended_atomics extensions are supported and have been enabled.

**Comment by kpet** [comment]
All PRs merged, closing.
