### ISSUE TITLE
cl21 cl22: cl_khr_spirv_no_integer_wrap_decoration - Test compiler - extend known extensions string

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#37]
The extension cl_khr_spirv_no_integer_wrap_decoration has been recently ratified. The change in test_compiler is required to extend known extension array of strings (otherwise the test will failed for platforms that supports this extension).

**Comment by kpet** [comment]
All PRs merged, closing.
