### ISSUE TITLE
CSV executable names don't match cmake or build output

### ISSUE THREAD

**Issue by aarongreig** [KhronosGroup/OpenCL-CTS#372]
While attempting to run conformance tests with `run_conformance.py` I noticed that the executables named in `test_conformance/opencl_conformance_tests_full.csv` don't match the names in any of the test CMakeLists, so the script can't find the test executables to run. For example the first test listed is `computeinfo/computeinfo`, but the computeinfo CMakeLists starts with `add_executable(conformance_test_computeinfo`, so the path to the test after building it is actually
`computeinfo/conformance_test_computeinfo`. I have a fix ready locally that renames the tests in all of the csvs to reflect the CMake, but I wanted to raise the issue here before opening a PR in case I'm missing something about script usage or the purpose of the csvs included in the repo.

**Comment by bhargavthriler** [comment]
@aarongreig during the CTS build, while generating config files change the `-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=./bin` to `-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=.`
This will put the output binaries to the location where `opencl_conformance_tests_full.csv` is searching, eg : `computeinfo/test_computeinfo`

Complete command:
before
`cmake -DCL_INCLUDE_DIR=${TOP}/OpenCL-Headers -DCL_LIB_DIR=${TOP}/OpenCL-ICD-Loader/build -DCL_LIBCLCXX_DIR=${TOP}/libclcxx -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=./bin -DOPENCL_LIBRARIES="-lOpenCL -lpthread"`
after
`cmake -DCL_INCLUDE_DIR=${TOP}/OpenCL-Headers -DCL_LIB_DIR=${TOP}/OpenCL-ICD-Loader/build -DCL_LIBCLCXX_DIR=${TOP}/libclcxx -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=. -DOPENCL_LIBRARIES="-lOpenCL -lpthread"`

**Comment by kpet** [comment]
@aarongreig  I believe this has now been fixed by @kbenzie's https://github.com/KhronosGroup/OpenCL-CTS/pull/705. Please re-open the issue if there are still name mismatches.
