### ISSUE TITLE
cl21 cl22 - New test for cl_khr_spirv_no_integer_wrap_decoration and SPV_KHR_no_integer_wrap_decoration extensions

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#38]
The extension cl_khr_spirv_no_integer_wrap_decoration has its corresponding spir-v extension SPV_KHR_no_integer_wrap_decoration. New test is needed to verify if offline compiler supports this extensions. The test proposal appear soon after sync with internal Khronos repository. New test will extend set of tests in spirv_new directory

**Comment by kpet** [comment]
PR merged, closing.
