### ISSUE TITLE
cl12: conversion reference functions on cl12 branch still using C types

### ISSUE THREAD

**Issue by aarongreig** [KhronosGroup/OpenCL-CTS#383]
Some of the saturated conversion reference functions on cl12_trunk are still using C types in their casts (such as in [char2uchar_sat](https://github.com/KhronosGroup/OpenCL-CTS/blob/d69c452a70a3a85c78c0a36e139fcc72f5044580/test_conformance/conversions/basic_test_conversions.c#L822)) while branches from cl 2.0 and up have since been updated to use [the cl types](https://github.com/KhronosGroup/OpenCL-CTS/blob/912bfbe4662f9bfd4f7dd17202878496bcf375cb/test_conformance/conversions/basic_test_conversions.c#L848) in the same code.

**Comment by kpet** [comment]
PR merged, closing.
