### ISSUE TITLE
cl12 test_sizeof should check sizeof(half) == 2

### ISSUE THREAD

**Issue by linnaea** [KhronosGroup/OpenCL-CTS#41]
It's currently checking for sizeof(half) == 8.

https://github.com/KhronosGroup/OpenCL-CTS/blob/cl12_trunk/test_conformance/basic/test_sizeof.c#L359

**Comment by kpet** [comment]
This will be fixed when we merge from the internal repo (already fixed there).

**Comment by alycm** [comment]
Thank you for the report, this is now resolved here as well (the original linked line now points to a check against 2).
