### ISSUE TITLE
Uncomment and re-integrate "not implemented" buffer tests.

### ISSUE THREAD

**Issue by aarongreig** [KhronosGroup/OpenCL-CTS#439]
The buffer tests `buffer_read_half`, `buffer_write_half` and `mem_alloc_ref_flags` hit the unimplemented case in `testHarness.c` and print something like:
```
mem_alloc_ref_flags test currently not implemented
```
This is due to how the buffer test lists are [defined](https://github.com/KhronosGroup/OpenCL-CTS/blob/0b9329a9d679bfe118ca7f4ee321a2a0a315d930/test_conformance/buffers/main.c#L50) in [both](https://github.com/KhronosGroup/OpenCL-CTS/blob/c1ef993f5e85bb1401834a85b506e4694a32adce/test_conformance/buffers/main.c#L50) branches and the existing test implementations being [commented out](https://github.com/KhronosGroup/OpenCL-CTS/blob/0b9329a9d679bfe118ca7f4ee321a2a0a315d930/test_conformance/buffers/test_buffer_read.c#L1145). It would be nice to re-integrate these tests by tweaking the existing test implementations to check if the tested feature is present before running anything and then re-enabling them in the function list.

**Comment by ellnor01** [comment]
Hi, I've been looking into this issue.
I can't find evidence that mem_alloc_ref_flags ever had any test code, and I am unclear from the name of the function exactly what it should be testing. 

Looking at similar tests there appears to be no equivalent test for CL_MEM_ALLOC_HOST_PTR or CL_MEM_USE_HOST_PTR?
