### ISSUE TITLE
SVM - svm_fine_grain_memory_consistency fail in case one of SVM devices do not support 64bit atomics 

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#440]
The test svm_fine_grain_memory_consistency  takes all visible devices into account while running. In situation when one device on the platform supports extensions and second not it returns failures. This is incorrect situation, all devices should be verified if required extensions are supported.
Solution:
Move checking extension exists for device to function create_cl_objects which discovers capable_devices for the test.

**Comment by kpet** [comment]
PR merged, closing.
