### ISSUE TITLE
test_SVM coarse-grain SVM buffer sync problem

### ISSUE THREAD

**Issue by hewj03** [KhronosGroup/OpenCL-CTS#450]
The following four tests has synchronize issues between two difference devices: 
svm_shared_address_space_coarse_grain_new_api
svm_shared_address_space_coarse_grain_old_api
svm_shared_sub_buffers
svm_cross_buffer_pointers_coarse_grain

For example, at first OpenCL kernel is executed on device A and it writes to a coarse-grain SVM buffer. Then OpenCL kernel on device B reads the SVM buffer and verify its correctness.
However, device B view of the SVM buffer is not updated after the first step. OpenCL kernel on device B sees outdated data.

**Comment by b-sumner** [comment]
I agree there is a problem, but I think there is a better solution than the one proposed.  I think the real problem in the multi-device case is that the verifier is not waiting for the creator.  But that is easy to fix using events.  The creator should produce a completion event, and the verifier should have that event in its event_wait_list.

**Comment by hewj03** [comment]
There is already a clFinish in create_linked_lists_on_device. So adding an event will not help.

**Comment by b-sumner** [comment]
Ugh.  Don't know how I missed those clFinish.  But their presence should guarantee that verify sees the results of create.  Which implementation are you seeing the problem on?

**Comment by hewj03** [comment]
We are seeing the problem of creating linked list on GPU OpenCL device and verify on CPU OpenCL device.
Only in the case of fine-grain SVM buffer, clFinish can guarantee that verify sees updates.
Coarse-grain SVM consistency model is like global memory, synchronization using map/unmap is necessary according to spec.

**Comment by b-sumner** [comment]
I do not believe mmap/munmap are required to synchronize.  For example, in Memory Ordering Rules: Host-side and Device-side Commands, there is this item in the list of synchronization rules: 8. If a host thread executes a clFinish call X, then the events of all commands enqueued prior to X in the command-queue global-synchronizes-with X.

**Comment by hewj03** [comment]
The test has two command queues, one for creator device A and another for verifier device B. clFinish in create_linked_lists_on_device only synchronizes commands in queue on creator device A.

**Comment by hewj03** [comment]
For coarse-grain SVM, map/unmap is only required to update memory between the host and a device.  It is not required to enforce consistency between devices.
So the proposed PR might not be proper. I'll close PR and this issue. We'll disable shared-context SVM test on failed implementation.
