### ISSUE TITLE
Remove debug flags from conversions and geometrics release tests

### ISSUE THREAD

**Issue by jlewis-austin** [KhronosGroup/OpenCL-CTS#468]
These test sets override any existing CMAKE_C_FLAGS_RELEASE flags and replace with flags disabling optimizations. 
The comment in conversions CMakeLists.txt is "# VS2005 AMD64 WAR (basic_test_conversions.c causes internal compiler error)" but it overrides the flags for all platforms. It builds fine on VS2015 and up at least.
For geometrics, the comment is "# VS2005 optimization WAR for geom_length" and flags are overridden for MSVC only.
Per @kpet comment, proposal is to remove all flag overrides and go from there. If any fixes are required, they should be done generically in source if possible or targeted to specific compilers/versions and documented as such.

**Comment by kpet** [comment]
Fixed by #704.
