### ISSUE TITLE
Missing coverage of memory_scope_sub_group

### ISSUE THREAD

**Issue by b-sumner** [KhronosGroup/OpenCL-CTS#51]
I may be missing something, but I don't find memory_scope_sub_group mentioned anywhere.  I don't believe there is coverage of this scope in any of the tests.

**Comment by kpet** [comment]
I think this is a duplicate of part of https://github.com/KhronosGroup/OpenCL-CTS/issues/24 that I raised a while back.

**Comment by b-sumner** [comment]
You're right.  I missed that.
