### ISSUE TITLE
Duplicate copies of Is{Double,Float}Subnormal

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#511]
We have several copies of these functions. We should have a single copy in the common code.

**Comment by jlewis-austin** [comment]
Per discussion with @kpet, expanding this to include IsHalfSubnormal. The common code should use the cl_half type, and all implementations should document the subtract 1 underflow trick used to exclude 0 from the detected subnormal range.

**Comment by ellnor01** [comment]
@jlewis-austin, is this issue then blocked by #452?

**Comment by jlewis-austin** [comment]
@ellnor01 Not necessarily, but it would be nice to get that one in first. I'm working on it now
