### ISSUE TITLE
image_streams tests don't handle CL_DEVICE_TYPE_DEFAULT correctly

### ISSUE THREAD

**Issue by jlewis-austin** [KhronosGroup/OpenCL-CTS#517]
The tests have codepaths specific to GPU devices, but can fail if the CL_DEVICE_TYPE_GPU isn't explicitly defined via the command line or environment variable. This works properly in cl12_trunk via a clGetDeviceInfo call to get the actual device type, but the call is missing in the master branch.

**Comment by kpet** [comment]
Thanks for reporting this. I've added it to the checklist for the merge of cl12_trunk into master so we don't lose track of this.

**Comment by kpet** [comment]
Even the code on cl12_trunk isn't fully correct: implementations that return GPU|DEFAULT as the device type for example aren't handle correctly.

**Comment by kpet** [comment]
Fixed by https://github.com/KhronosGroup/OpenCL-CTS/pull/611 (and previous changes). Remaining issues around comparing the device type for equality covered by https://github.com/KhronosGroup/OpenCL-CTS/issues/574.
