### ISSUE TITLE
Typo in include directory

### ISSUE THREAD

**Issue by b-sumner** [KhronosGroup/OpenCL-CTS#546]
The build scripts and travis file both run cmake setting CL_INCLUDE_DIR, and the root CMakeLists.txt checks for it.  But at the most important place, it appears there is a typo: https://github.com/KhronosGroup/OpenCL-CTS/blob/master/CMakeLists.txt#L170

I assume that "OPENCL_INCLUDE_DIR" is supposed to be "CL_INCLUDE_DIR"?

**Comment by kpet** [comment]
It is set to `CL_INCLUDE_DIR` here: https://github.com/KhronosGroup/OpenCL-CTS/blob/master/CMakeLists.txt#L117.
I don't think it's broken but there's no reason to have both. I think we should get rid of line 117 and use `CL_INCLUDE_DIR` directly on line 170.

**Comment by b-sumner** [comment]
Sorry about that, not sure how I missed it.  I agree it might be better to stick to just one.  Closing.

**Comment by kpet** [comment]
Re-opening so we don't forget to remove the redundant variable.
