### ISSUE TITLE
computeinfo: size_t is printed as signed integer

### ISSUE THREAD

**Issue by ltowarek** [KhronosGroup/OpenCL-CTS#554]
Currently capabilities with size_t type like CL_DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE
are printed as signed values for example:
CL_DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE == -881700864

**Comment by kpet** [comment]
Both PRs merged, closing.
