### ISSUE TITLE
Ignore padding bit of CL_UNORM_SHORT_555 for clFillImage

### ISSUE THREAD

**Issue by StuartDBrady** [KhronosGroup/OpenCL-CTS#559]
In `images/clFillImage/test_fill_generic.cpp`, `test_fill_image_generic()` includes code to ignore the padding bits for `CL_UNORM_INT_101010`, but the padding bits of `CL_UNORM_SHORT_555` are not ignored.

Also, the code to ignore padding bits works by modifying the test data, which will affect error message produced by the test, if it should fail. It may be better to ignore the padding bits when comparing pixels, instead of modifying the test data.

Note that in `images/clCopyImage/test_copy_generic.cpp`, `test_copy_image_generic()` includes similar code to compare source and destination images, although there is no code to ignore padding bits in this case. It may be clearer to use a single image comparison function for both `test_fill_image_generic()` and `test_copy_image_generic()`, even it is not a problem in practice that `testCopyImage` currently checks the padding bits.

**Comment by kpet** [comment]
@StuartDBrady Was this fixed by https://github.com/KhronosGroup/OpenCL-CTS/pull/1184? If yes could you close this issue please?

**Comment by StuartDBrady** [comment]
Fixed by #1184.
