### ISSUE TITLE
"half" is not handled in cl12_trunk

### ISSUE THREAD

**Issue by ian37** [KhronosGroup/OpenCL-CTS#563]
https://github.com/KhronosGroup/OpenCL-CTS/blob/6a64c5a0c74b9e4a83025628f2cdb746647cdfb1/test_conformance/basic/test_sizeof.c#L42

"half" is not handled in cl12_trunk, and only "double" is processed.
I find that this problem has been fixed in the master. Please synchronize the code to the cl12_trunk.
The related code in master is as below.
```
    if (!strncmp(type, "double", 6))
    {
        sizeof_kernel_code[0] = "#pragma OPENCL EXTENSION cl_khr_fp64 : enable\n";
    }
    else if (!strncmp(type, "half", 4))
    {
        sizeof_kernel_code[0] = "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n";
    }
```

**Comment by kpet** [comment]
Could you propose a PR please?

**Comment by kpet** [comment]
cl12_trunk was merged into master where this is handled. Please use the master branch. Closing.
