### ISSUE TITLE
Extra spaces in kernel source

### ISSUE THREAD

**Issue by luoanquan** [KhronosGroup/OpenCL-CTS#567]
https://github.com/KhronosGroup/OpenCL-CTS/blob/6a64c5a0c74b9e4a83025628f2cdb746647cdfb1/test_conformance/thread_dimensions/test_thread_dimensions.c#L234
Extra spaces in "final_x_    size" may cause compilation errors, which appears to have been modified in the master branch.

**Comment by kpet** [comment]
Fixed on master. Closing.
