### ISSUE TITLE
Suggestion of removing memcpy of binaries in "test_api binary_create" on branch cl12_trunk

### ISSUE THREAD

**Issue by aranpaop** [KhronosGroup/OpenCL-CTS#591]
On branch **_cl12_trunk_**, "test_api binary_create" has compared the binaries get from programs created by **_clCreateProgramWithSource_** and **_clCreateProgramWithBinary_**:
```
    if( memcmp( binary, binary2, binarySize ) != 0 )
    {
        log_error( "ERROR: Program binary is different when loaded from binary!\n" );
        free(binary2);
        free(binary);
        return -1;
    }
```
There is:
> The decision on which information is retured in the binary is up to the OpenCL implementation.

in OpenCL1.2 SPEC 5.6.7, table 5.12 when introducing **_CL_PROGRAM_BINARIES_**.
On branch **_master_**, the memcpy of binaries have already been removed and only check the calculation results of binaries. I think the test of cl12 can sync to cl2x.

**Comment by kpet** [comment]
cl12_trunk was merged into master where this code is correct. Please use the master branch to test 1.2 implementations.
