### ISSUE TITLE
De-duplicate and improve PrintArch functions

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#595]
See https://github.com/KhronosGroup/OpenCL-CTS/pull/552

**Comment by kpet** [comment]
Proposed PR against cl12_trunk: https://github.com/KhronosGroup/OpenCL-CTS/pull/596

**Comment by bhargavdas** [comment]
New PR proposed for master #601

**Comment by kpet** [comment]
Solved by #601
