### ISSUE TITLE
Use is_extension_available throughout the code base

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#627]
A number of tests have got their own code using `CL_DEVICE_EXTENSIONS` to check for the presence of extensions. All tests should be using `is_extension_available` and it should be modified to handle errors by throwing exceptions.

**Comment by ellnor01** [comment]
I will work on this

**Comment by kpet** [comment]
Thanks! Given the scale of the change, this is probably best tackled with several PRs.
