### ISSUE TITLE
Min/Max Compiler Versions are Unspecified

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#640]
CTS doesn't list a minimum or maximum compiler version with which one might expect to be able to build the tests.

I'd suggest a starting point for the minimum version of gcc would where C++11 was introduced (gcc 4.8).

**Comment by kpet** [comment]
Isn't that something we should capture under #470?

**Comment by Jeremy-Kemp** [comment]
Yes, that makes sense. Closing.
