### ISSUE TITLE
Ignore vendor extensions when querying host command queue properties

### ISSUE THREAD

**Issue by lakshmih** [KhronosGroup/OpenCL-CTS#642]
The presence of the flags related to vendor extensions on host queue properties is causing the api and api_compatibility tests to fail.  Ignore vendor extensions when querying host command queue properties.

**Comment by lakshmih** [comment]
@bashbaug @kpet  requesting review for this.

**Comment by kpet** [comment]
@lakshmih I did comment on your PR :).

**Comment by lakshmih** [comment]
This same fix needs to be made in the compatibility api test as well

**Comment by alycm** [comment]
I believe this was addressed by merging: https://github.com/KhronosGroup/OpenCL-CTS/pull/957

Closing.
