### ISSUE TITLE
align_malloc broken for clReadWrite tests on Linux

### ISSUE THREAD

**Issue by jrprice** [KhronosGroup/OpenCL-CTS#644]
In #631, @kpet introduced a new `align_malloc` function. This is crashing for me on Linux for the `images/clReadWrite` suite.

The old code used `memalign` for these allocations on Linux in the image suites, whereas the new function uses `posix_memalign`. The latter has a stricter requirement on its arguments [1], in particular:

> alignment ... must be a power of two ___and a multiple of sizeof(void *)___

This breaks the image tests, as they often request an alignment which matches the size of the pixel, which is typically less than `sizeof(void*)`. The most general solution would be to pick the alignment which is the least-common-multiple of the requested alignment and `sizeof(void*)`.

[1] http://man7.org/linux/man-pages/man3/posix_memalign.3.html

**Comment by kpet** [comment]
Sorry for that. I'll create a PR with a fix.
