### ISSUE TITLE
Test SVM: pointer_passing - passing unmapped pointer to clSetKernelArgSVMPointer is incorrect

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#660]
See 
Unmapping: https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/SVM/test_pointer_passing.cpp#L76

Usage:
https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/SVM/test_pointer_passing.cpp#L84

There should be assigned pbuf not pBuf to pChar.

**Comment by kpet** [comment]
The problem isn't really using an "unmapped pointer", rather using a map pointer from a buffer created from an SVM pointer where only an SVM pointer is accepted.
