### ISSUE TITLE
No test status when TEST_SKIP in case of InitCL

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#664]
Hi 
I see truncated log from test binary in case of cases for OpenCL 2.X and executed on platform OpenCL 1.X
example:
`test_device_timer.exe
 Initializing random seed to 0.
Requesting Default device based on command line for platform index 0 and device index 0
Compute Device Name = Intel(R) UHD Graphics 605, Compute Device Vendor = Intel(R) Corporation, Compute Device Version = OpenCL 1.2 NEO , CL C Version = OpenCL C 1.2
Supports single precision denormals: YES
sizeof( void*) = 8  (host)
sizeof( void*) = 4  (device)
`
This situation is related with PR #628 

We should print something on output in situation of `return TEST_SKIP;` 
However I am wondering how and what . The problem is that we do not reach calling function https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/testHarness.cpp#L471
where print_results function is called. 
Do you have any suggestion what should be printed in case of 
this skip:
https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/device_timer/main.cpp#L41

and this:
https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/device_timer/main.cpp#L62

**Comment by kpet** [comment]
I agree we should do something there. This also relates to https://github.com/KhronosGroup/OpenCL-CTS/issues/617.

Instead of exiting on https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/testHarness.cpp#L452 we could just remember an exit code (or lack of need to exit) and have a bit of code to handle that case after the block that currently deals with the return from `deviceCheckFn`. We know the total number of tests so we could report `FAILED x of x tests` or `SKIPPED x of x tests`.

**Comment by gwawiork** [comment]
ok I understand then I think we should move `deviceCheckFn` inside the `parseAndCallCommandLineTests` rigth ?

**Comment by kpet** [comment]
I don't think that's necessary just now. We're probably going to need it for https://github.com/KhronosGroup/OpenCL-CTS/issues/617 though.

**Comment by gwawiork** [comment]
Without calling `parseAndCallCommandLineTests` we will be always skip and exit on the first test case in the test_list. Are you ok with this ?

**Comment by kpet** [comment]
Not sure I'm following, `deviceCheckFn` controls the execution of all the tests in a given suite.

**Comment by gwawiork** [comment]
Then ok. My proposal:
test_device_timer.exe *
 Initializing random seed to 0.
Requesting Default device based on command line for platform index 0 and device index 0
Compute Device Name = Intel(R) UHD Graphics 605, Compute Device Vendor = Intel(R) Corporation, Compute Device Version = OpenCL 1.2 NEO , CL C Version = OpenCL C 1.2
Supports single precision denormals: YES
sizeof( void*) = 8  (host)
sizeof( void*) = 4  (device)
Test skipped (requires at least version 2.1, but the device reports version 1.2)  `message printed from the main.cpp of the test case`
Test skipped while initialization `message printed from test harness`
PASSED test.

**Comment by gwawiork** [comment]
I've pushed out proposal. I this will be accepted I will modify other tests accordingly . 
What I see:
There is a need in tests with InitCL cleanup tabs to spaces 
More tests need add minimum version 2.0
