### ISSUE TITLE
How to run tests using `offline` and `spir-v` compilation modes

### ISSUE THREAD

**Issue by kbenzie** [KhronosGroup/OpenCL-CTS#689]
`master` branch changes seem to have dropped some files, relevant for using the `--compilation-mode {offline,spir-v}` test options, which were present in the original SPIR-V testing [patch](https://github.com/KhronosGroup/OpenCL-CTS/commit/4c31b69980d979eeb1bafaa45baa3e6fd8082013), specifically the `test_conformance/build_script_{offline,spirv}.py` scripts. Were these file drops accidental?

Also, `cl_offline_compiler` is mentioned in a number of places, and is used by `test_conformance/generate_spirv_offline.py` and in `test_harness` code, the only reference which has any information is `test_harness/cl_offline_compiler-interface.txt`, is the intent for the tester to implement this interface? Should there be a default implementation akin to dropped `test_conformance/build_script_{offline,spirv}.py`? 

I might be missing something but documentation around these testing configurations seems to be lacking. Things it would be useful to know:

* What files/tools/scripts are required?
* What steps are required?

**Comment by gwawiork** [comment]
Regarding run:

The interface has to match to this:
   parser.add_argument('--mode', default=r'spir-v',help='Mode')
   parser.add_argument('--source',help='source')
   parser.add_argument('--output',help='output')
   parser.add_argument('user_build_options',type=str,nargs='*',help='user_build_options')
   parser.add_argument('--cl-device-info',help='cl-device-info')

Example of execution (generation):
test_bruteforce -w acos --compilation-mode spir-v --compilation-cache-mode overwrite --compilation-program c:\SPIRV\generate_today\build_script_spirv.py --compilation-cache-path c:\SPIRV\generate_today\spirv_bruteforce

I can prepare example script in python next week to run this spirv if you want

**Comment by kbenzie** [comment]
@gwawiork thanks, an example script to work from could be useful.

Documentation for the requirements and process in the repository itself would be most useful I suspect, the `README` is extremely sparse currently.

I've also noticed a related issue in the `opencl_conformance_tests_21_full_spirv.csv` and `opencl_conformance_tests_generate_spirv.csv` files, where `-offlineCompiler spir_v`, `cache .`, and `generate .` command line arguments are used but these are not reported as being supported in the test executable `--help` messages. I suspect they have not been updated to use `--compilation-{mode,cache-mode,cache-path,program}` unified set of command line arguments.

**Comment by gwawiork** [comment]
For sure we have here a little mess. Each thing you have pointed out could be filed as github Issue.

**Comment by kbenzie** [comment]
Okay, to summarise the separate issues are:

* [ ] Missing `test_conformance/build_script_{offline,spirv}.py` scripts.
* [ ] Missing example `cl_offline_compiler` script.
* [ ] Missing documentation.
* [ ] CSV files need updated.

I'll tick these off as I create the tickets, then close this one.

**Comment by kpet** [comment]
The first one is not an issue. It's a consequence of the new unified approach to offline and spirv compilation. All the others need addressing.

**Comment by kbenzie** [comment]
@kpet sorry didn't see your comment before I created the new ticket.

**Comment by kbenzie** [comment]
Separate tickets created, so closing this.
