### ISSUE TITLE
CSV files for offline/spirv mode need updated

### ISSUE THREAD

**Issue by kbenzie** [KhronosGroup/OpenCL-CTS#698]
Splitting out from #689 following discussions with @gwawiork and @kpet 

The `opencl_conformance_tests_21_full_spirv.csv` and `opencl_conformance_tests_generate_spirv.csv` files still reference the now defunct command line arguments `-offlineCompiler spir_v`, `cache .`, and `generate .` which are no longer supported by the conformance tests after switching to unified offline/spirv compilation. The CSV files should be updated to use the new `--compilation-{mode,cache-mode,cache-path,program}` set of command line arguments.

**Comment by kpet** [comment]
Fixed by #774, closing.
