### ISSUE TITLE
SVM: Enqueue API Assuming Fine Grain System

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#707]
I believe this test is incorrectly assuming that fine grain system support is always available.

At this point, the test assigns a pointer from a host vector (`srcHostData.data` is `vector::<cl_uchar>`):
https://github.com/KhronosGroup/OpenCL-CTS/blob/efaf0240350419b701b028f281690258e38cf71c/test_conformance/SVM/test_enqueue_api.cpp#L167
Later, the pointer is used directly in SVM calls. E.g. this one a few lines later:
https://github.com/KhronosGroup/OpenCL-CTS/blob/efaf0240350419b701b028f281690258e38cf71c/test_conformance/SVM/test_enqueue_api.cpp#L177
I think that if either `test_case.dstAlloc` or `test_case.srcAlloc` are `host`, then the test case should be skipped if `CL_DEVICE_SVM_FINE_GRAIN_SYSTEM` is not supported by the device.

Could someone else take a look to check whether they agree please?

**Comment by kpet** [comment]
`clEnqueueSVMMemcpy` can take either a host pointer or an SVM allocation:

>dst_ptr is the pointer to a host or SVM memory allocation where data is copied to.
>src_ptr is the pointer to a host or SVM memory allocation where data is copied from.

The test looks valid to me.

**Comment by Jeremy-Kemp** [comment]
Ok, I'd interpreted the wording badly. Thanks for clarifying. Closing.
