### ISSUE TITLE
SPIR-V handling on different OpenCL devices version

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#716]
I have proposal how to handle SPIR-V compilation on different OpenCL devices.

**Comment by gwawiork** [comment]
Solution:
for devices < 2.1 - TEST_SKIP
for devices 2.1 and 2.2 when SPIR-V not found in CL_DEVICE_IL_VERSION - TEST_FAIL. Otherwise go testing
for devices > 2.2  when SPIR-V not found in CL_DEVICE_IL_VERSION - TEST_SKIP. Otherwise go testing

**Comment by alycm** [comment]
Hello, what about devices < 2.1 that report support for the `cl_khr_il_program` extension?

**Comment by gwawiork** [comment]
Looks I forgot this path.

**Comment by gwawiork** [comment]
@alycm I pushed out changes for cl_khr_il_program extension.  Please check if my proposal looks good. Thanks.

**Comment by alycm** [comment]
Thank you @gwawiork, a colleague is trying it out.
