### ISSUE TITLE
Mismatched new[]/delete and new/free

### ISSUE THREAD

**Issue by jrprice** [KhronosGroup/OpenCL-CTS#723]
The `test_loops.cpp` files in the image tests perform mismatched allocation/deallocation in their helper routines.

In clCopyImage/clFillImage/kernel_image_methods, we [allocate with `new[]`](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/images/clCopyImage/test_loops.cpp#L199) and then [deallocate with `delete`](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/images/clCopyImage/test_loops.cpp#L255) (instead of `delete[]`).
clReadWriteImage used to do this but was fixed in #481.

In clGetInfo/kernel_read_write, we [allocate with `new []` and then convert to a `BufferOwningPtr`](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/images/clGetInfo/test_loops.cpp#L184-L185), which [deallocates with `free`](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/typeWrappers.h#L290).

I suspect `BufferOwningPtr` is used to avoid leaking memory if the function returns early for any reason. Using `std::vector` for these allocations would be a straightforward way of avoids leaks and fixing both of the above mismatches.

I also note that the helper routines in these files are all fairly similar (although not identical), and can probably be refactored into a single common header (though I haven't examined the differences closely yet).

**Comment by jrprice** [comment]
PR #732 by @ellnor01  broke most of CTS for us because of this same issue. A `malloc` was switched to a `new[]`, the result is captured by a `BufferOwningPtr`, which means it is later deallocated with `free`.

This issue stems from the fact that we are in a strange limbo between C and C++. Can we commit to moving towards C++ only at this point, starting by removing all `malloc`/`free` usages?

**Comment by kpet** [comment]
Yes, moving towards C++ sounds good.
