### ISSUE TITLE
Is there a Conformance Test branch for OpenCL 3.0 ? Considering that OpenCL 3.0 has been released.

### ISSUE THREAD

**Issue by luoanquan** [KhronosGroup/OpenCL-CTS#750]

**Comment by kpet** [comment]
The conformance tests for OpenCL 3.0 haven't been fully developed yet. They will be available on the master branch in this repository. I've created https://github.com/KhronosGroup/OpenCL-CTS/projects/1 to track the work and will populate this soon.

**Comment by luoanquan** [comment]
Thank you very much for your reply. May I ask if we have a plan? when will we finally officially release the OpenCL 3.0 conformance test branch or compatible with OpenCL 3.0 CTS on master branch？

**Comment by alycm** [comment]
Hello, there is now a tag of the CTS that contains 3.0 testing: https://github.com/KhronosGroup/OpenCL-CTS/releases/tag/v2020-10-01-00

The CTS will of course continue to improve and there will be further tags, but on the basis of the above tag I'm going to close this issue.

If you hit any problems when trying out the CTS then please file issues or pull requests!
