### ISSUE TITLE
OpenCL 3.0 feature macros CTS test

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#755]
I am going to prepare CTS test  to validate feature macros in OpenCL 3.0
**Where:** Inside of test_compiler suite
**How:** Similar to test_image_macro.cpp . The test will verify if particular param_names values returned by clDeviceInfo are equal to values that corresponds to turn on/off feature. Then appropriate kernel will be executed to validate feature turn on/off
**Test scope:**
- [x] __opencl_c_3d_image_writes
- [x] __opencl_c_atomic_order_acq_rel
- [x] __opencl_c_atomic_order_seq_cst
- [x] __opencl_c_atomic_scope_device
- [x] __opencl_c_atomic_scope_all_devices
- [x] __opencl_c_device_enqueue
- [x] __opencl_c_generic_address_space
- [x] __opencl_c_pipes
- [x] __opencl_c_program_scope_global_variables
- [x] __opencl_c_read_write_images
- [x] __opencl_c_subgroups
- [x] __opencl_c_work_group_collective_functions

**Comment by kpet** [comment]
Thanks! Could you expand the how a bit please? It's unclear to me whether you want to test consistency between the feature macros exposed by the compiler and the runtime or if you want to test feature macros vs. runtime device queries for the features or both or something else :).

**Comment by gwawiork** [comment]
Hmm... I want to test if feature macro variable is defined in kernel body (compiler should enabled it base on runtime information) against the device query return 'feature on'.
Example:
If device informs that CL_​DEVICE_​DEVICE_​ENQUEUE_​SUPPORT == true then kernel execution
with code like:
`#ifndef __opencl_c_device_enqueue`
`ERROR;`
`#endif``
should compile with successes because ERROR is not added to the kernel body.
