### ISSUE TITLE
Relaxed math testing uses Full Profile ULP requirements for Embedded Profile

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#760]
The embedded profile ULP requirements for fast relaxed math are not considered.

**Comment by alycm** [comment]
Related, but distinct ticket: https://github.com/KhronosGroup/OpenCL-CTS/issues/703

I mention it because  I suspect that solving both problems at once is probably as easier as solving either alone.

**Comment by Jeremy-Kemp** [comment]
I'd like to start looking at this.

My initial proposal is to keep it simple, and add something along the lines of `float relaxed_error_embedded` to the `Func` struct in `FunctionList.h`.

The current logic for changing the required ULP for the relaxed builtins would be slightly modified to check whether the device is `EMBEDDED_PROFILE` and if so, use `relaxed_error_embedded` instead.

If that is acceptable, I'll create a PR.

Feedback is most welcome.

**Comment by EwanC** [comment]
Given there isn't separate ULP requirements defined for either double or half precision embedded relaxed math, this approach makes sense to me @Jeremy-Kemp

**Comment by Jeremy-Kemp** [comment]
Thanks for the feedback.

If there are no objections, please could someone move this issue to "In Progress" in the 3.0 project and I'll get started.

**Comment by kpet** [comment]
@Jeremy-Kemp Now assigned to you and marked as "In Progress".
