### ISSUE TITLE
Range checks take absolute value of unsigned integer

### ISSUE THREAD

**Issue by jrprice** [KhronosGroup/OpenCL-CTS#783]
[Some verification code](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/math_brute_force/unary_u.cpp#L318) in `math_brute_force` calls `fabsf()` with a `cl_uint` argument:
```
cl_uint *s = (cl_uint*) gIn;
...
if( isRangeLimited && fabsf(s[j]) > MAKE_HEX_FLOAT(0x1.0p16f, 0x1L, 16) && fabsf(s[j]) < INFINITY )
```

Found when enabling `-Werror`. I wasn't sure what the intent of this is so have left it for now (can these checks just be removed or is there a bug here?). This will be dealt with via `-Wno-error=absolute-value` in the root `CMakeLists.txt` until fixed.

**Comment by mantognini** [comment]
This was addressed in #1237 and #1252 removed `-Wno-error=absolute-value` from CMake.
