### ISSUE TITLE
CL3 subgroups optionality

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#795]
At least:

[ ] Is anything needed beyond checks for cl_khr_subgroups?
[ ] Need to add checks for lack of subgroup IFP?

**Comment by bashbaug** [comment]
I think this issue can be closed now.

For item (1), we've added additional checks for `CL_DEVICE_MAX_NUM_SUB_GROUPS` in #581.

For item (2), we have a check for `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS` in test_ifp.cpp.

**Comment by alycm** [comment]
Agreed, this appears to be done now.
