### ISSUE TITLE
error: ignoring return value of freopen

### ISSUE THREAD

**Issue by mantognini** [KhronosGroup/OpenCL-CTS#809]
Here:

https://github.com/KhronosGroup/OpenCL-CTS/blob/8579e61401d66d9c1e9e2903cf4eaad1c8d5afdc/test_conformance/printf/test_printf.cpp#L147

the return value is ignored. This cause a compilation error when using a release build of the CTS on my system (the main relevant info should be: GCC 7.5 and its default standard library on Ubuntu 18.04, libstdc++).

```
../test_conformance/printf/test_printf.cpp: In function 'int acquireOutputStream()':
../test_conformance/printf/test_printf.cpp:147:12: error: ignoring return value of 'FILE* freopen(const char*, const char*, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
     freopen(gFileName,"w",stdout);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

The fix is probably trivial, however it might be better to disable -Werror by default as a general rule because build will fail on a slightly different system than the one used for development/testing.

**Comment by kpet** [comment]
Being addressed by https://github.com/KhronosGroup/OpenCL-CTS/pull/801

**Comment by mantognini** [comment]
Glad to see this already being addressed. I wonder what is your opinion (and others') on my comment about not using -Werror by default.

**Comment by kpet** [comment]
We did enable it recently to get feedback from the CI on silly code issues that show up as warnings. The discussion was in https://github.com/KhronosGroup/OpenCL-CTS/pull/782.

**Comment by jlewis-austin** [comment]
verified fixed in same environment

**Comment by mantognini** [comment]
Feel free to close this ticket if there is no strong interest to remove `-Werror` from non-CI environment.
