### ISSUE TITLE
align_malloc fails to alloc memory for RGB float textures on Windows

### ISSUE THREAD

**Issue by jenatali** [KhronosGroup/OpenCL-CTS#822]
RGB textures would request 12-byte aligned. The _aligned_malloc function used requires power-of-two alignment.

**Comment by kpet** [comment]
I'm guessing we want to modify the calling code. Where is the user making this call?

**Comment by jenatali** [comment]
imageHelpers.cpp, two call sites using:
```
char *data = (char *)align_malloc(allocSize, get_pixel_size(imageInfo->format));
```

**Comment by kpet** [comment]
Yeah, that looks obviously wrong. Two ideas come to mind:
- introduce a `get_pixel_alignment` function
- round up to the next power of 2 as part of calling `align_malloc`.

I guess the preference would depend on the surrounding code and how reusable we want this to be.

@jenatali Would you be willing to propose a PR?

**Comment by jenatali** [comment]
Yeah, I'll do that today. I have a change I'm using to test locally, though I like your naming of `get_pixel_alignment` better than my `get_pixel_size_for_malloc`.
