### ISSUE TITLE
Floating-point arithmetic question

### ISSUE THREAD

**Issue by julienhascoet** [KhronosGroup/OpenCL-CTS#835]
Dear all,

The geometrics test performs computation in doubles for float computations.

We are wondering if this is legal regarding the specification, for instance we find comments as follow in the geometrics test:

`// We calculate the distance as a double, to try and make up for the fact that`
`// the GPU has better precision distance since it's a single op`
or
`// We calculate everything as a double, to try and make up for the fact that`
`// the GPU has better precision distance since it's a single op`

Indeed, should we promote everything to double for intermediate computations inside OpenCL builtins (distance, length, normalize) ?
If this is only for GPU, perhaps we may add something like this and make it configurable via cmake:

[geometric_fp32_ieee.txt](https://github.com/KhronosGroup/OpenCL-CTS/files/4837209/geometric_fp32_ieee.txt)

Thanks for your help,

Julien

**Comment by jlewis-austin** [comment]
@julienhascoet since the accuracy requirements are referenced to the infinitely precise result, I agree that all intermediate precision computations should be done in double, regardless of device type. It looks like the current code is doing that--are you seeing otherwise?

**Comment by julienhascoet** [comment]
@jlewis-austin thank you, yes the current code does computation in double even for float, and then the result in double is cast to float to perform integrity check for the float case.

I was wandering it could be illegal to perform double computations inside OpenCL builtin taking float as input(s) (ie: distance, length, normalize). You also have a lower performance while performing double computation inside builtins that take float as input(s).
If the OpenCL programmer wants double, he just uses the double flavour of the builtin.

See my patch geometric_fp32_ieee.txt in the original post.

**Comment by jlewis-austin** [comment]
@julienhascoet the code you pointed out is only for host execution to compute the "infinitely precise" reference. It says nothing about how the builtins themselves must be implemented. The implementation can do whatever it wants as long as it meets the ulp requirements (which are set up such that a pure float implementation will meet the requirement).
I did look at the patch; I just don't see any justification for making the reference computation less accurate. This assumes the host running the CTS supports double precision--if that's a concern, then I think that's a much bigger discussion.

**Comment by julienhascoet** [comment]
@jlewis-austin I understand thank you. I'll try to explain the issue with an example:

In the geometric geom_length test, here is the output I get without the patch for the tests of the builtin: float length(float x)

`geom_length...
ERROR: Data sample 4 at size 1 does not validate! Expected (0x1p+64), got (inf), source (0x1p+64), ulp 309485009821345068724781056.000000
	vector: { 0x1p+64 }   length vector size 1 FAILED
ERROR: Data sample 4 at size 2 does not validate! Expected (0x1p+64), got (inf), source (0x1p+64), ulp 309485009821345068724781056.000000
	vector: { 0x1p+64, 0x1.fd96e8p+7 }   length vector size 2 FAILED
ERROR: Data sample 4 at size 3 does not validate! Expected (0x1p+64), got (inf), source (0x1p+64), ulp 309485009821345068724781056.000000
	vector: { 0x1p+64, 0x1.3d4c6p+7, 0x1.1bb1ep+8 }   length vector size 3 FAILED
ERROR: Data sample 4 at size 4 does not validate! Expected (0x1p+64), got (inf), source (0x1p+64), ulp 309485009821345068724781056.000000
	vector: { 0x1p+64, -0x1.817238p+7, -0x1.7114ep+8, -0x1.709f8p+8 }   length vector size 4 FAILED
geom_length FAILED
PASSED sub-test.
FAILED test.`

- As we can see the conformance is expecting 0x1p+64 and our OpenCL device implementation returns inf, making the test marked as failed. The float length(float x) builtin takes as input a float and the length is computed as follow: sqrt(x²)
- In float, 0x1p+64 ² overflows and that's why we get inf and it does not match with the conformance.

To make it match, we need to promote float x² to double x² so it won't overflow. But is this legal ? Float computations are more efficient, and if we must promote float builtins to double for internal computations we lose performance.

But, if the spec says it this, then I'll patch the implementation to make the use of double for intermediate computations to avoid the overflow of the float.

Thank you for your time.

**Comment by EwanC** [comment]
> To make it match, we need to promote float x² to double x² so it won't overflow. But is this legal ? Float computations are more efficient, and if we must promote float builtins to double for internal computations we lose performance.

@julienhascoet Internally promoting to double is legal, but instead to keep float performance you could scale the input for large values in your implementation and continue to use 32-bit float operations.

**Comment by jlewis-austin** [comment]
@julienhascoet thanks that makes more sense. Internal overflow is something that's always an issue, even for the most precise data type available--in that case the scaling @EwanC mentioned is the only solution.
The OpenCL_C-2.0 spec is explicit about that requirement:
`distance(x, y) calculates the distance from x to y without overflow or extraordinary precision loss due to underflow`

**Comment by julienhascoet** [comment]
@jlewis-austin and @EwanC Thank you for your help.

I patched our implementation to make it fits the requirements.

Thanks again.
