### ISSUE TITLE
Update conformance runner csv files for CL 3.0

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#863]
The csv's need updating to reflect the required tests that must pass for an implementation to be conformant.

**Comment by Jeremy-Kemp** [comment]
I'll submit a PR for this in the morning. Currently planning on dropping the API specific files at the same time.

**Comment by alycm** [comment]
Closing due to https://github.com/KhronosGroup/OpenCL-CTS/pull/971 having merged.
