### ISSUE TITLE
Lack of cl_khr_3d_image_writes extension causes failure in test_image_streams for CL1.2

### ISSUE THREAD

**Issue by jenatali** [KhronosGroup/OpenCL-CTS#872]
In `test_image_set` in test_loops.cpp, there's this code:
```c++
    if ( ( 0 == is_extension_available( device, "cl_khr_3d_image_writes" )) && (imageType == CL_MEM_OBJECT_IMAGE3D) && (formatTestFn == test_write_image_formats) )
    {
        gFailCount++;
        log_error( "-----------------------------------------------------\n" );
        log_error( "FAILED: test writing CL_MEM_OBJECT_IMAGE3D images\n" );
        log_error( "This device does not support the mandated extension cl_khr_3d_image_writes.\n");
        log_error( "-----------------------------------------------------\n\n" );
        return -1;
    }
```

For OpenCL1.2, this extension is optional (https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_DEVICE_EXTENSIONS): 

>Additionally, the following Khronos extension names must be returned by all devices that support OpenCL 2.0, OpenCL 2.1, or OpenCL 2.2. Note that these Khronos extension names are not required for devices supporting OpenCL 3.0:
>
>cl_khr_3d_image_writes
>...

**Comment by bashbaug** [comment]
Good catch.  I think it should be sufficient to skip this test, similar to the way tests are skipped immediately following this check if testing mipmaps on devices that do not support the mipmap extensions.  Will this work for you?

```c
    if ( gTestMipmaps )
    {
        if ( 0 == is_extension_available( device, "cl_khr_mipmap_image" ))
        {
            log_info( "-----------------------------------------------------\n" );
            log_info( "This device does not support cl_khr_mipmap_image.\nSkipping mipmapped image test. \n" );
            log_info( "-----------------------------------------------------\n\n" );
            return 0;
        }
...
```

We'd probably want to keep failing the test if `cl_khr_3d_image_writes` isn't supported for an OpenCL 2.0, 2.1, or 2.2 devices for now, but ultimately I think these checks should move into a different "consistency" test instead.

**Comment by jenatali** [comment]
Yep, such a change sounds like it would work. I see the 2.0+ requirement for `cl_khr_3d_image_writes` is checked by test_api's `test_min_max_device_version` sub-test.
