### ISSUE TITLE
Test ctz under OpenCL 3.0

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-CTS#882]
Regarding the work item "Test ctz under OpenCL 3.0":

The existing `test_integer_ops` should pretty much work as-is, it just needs to be updated to pass `-cl-std=CL3.0` for an OpenCL 3.0 device rather than `-cl-std=CL2.0`.  The `integer_ops` tests are already running for OpenCL 1.x devices, so I don't think any other changes will be required.

**Comment by FranklandJack** [comment]
@bashbaug I actually have a local patch for this I was working on yesterday but haven't opened a PR for yet.

**Comment by bashbaug** [comment]
Fixed by #917 - closing.
