### ISSUE TITLE
Testing Creating 2D Images from Buffers for OpenCL 3.0

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-CTS#889]
Changes required for Creating 2D Images from Buffers for OpenCL 3.0:

Two places need to be updated to test the device queries CL_DEVICE_IMAGE_PITCH_ALIGNMENT and CL_DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT in addition to the `cl_khr_image2d_from_buffer` extension:

1. ComputeInfo ([link](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/computeinfo/main.cpp#L1169)).

2. test_image_streams (several places, example [here](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/images/kernel_read_write/main.cpp#L130)).

These changes are only needed if an implementation decides to support Creating 2D Images from Buffers but does NOT support the `cl_khr_image2d_from_buffer` extension, so they may not be required in practice.

This was originally tracked by the item "Check that no additional checks are needed beyond check for cl_khr_image2d_from_buffer" in #773.

**Comment by kpet** [comment]
One of my worries was that the extension/functionality was mandatory on 2.0 but has become optional in 3.0.

**Comment by bashbaug** [comment]
Given https://github.com/KhronosGroup/OpenCL-Docs/pull/410, which requires OpenCL 3.0 implementations to report `cl_khr_image2d_from_buffer` when the optional feature Creating 2D Images from Buffers is supported, I don't believe there is anything more to do for this issue and the existing checks for `cl_khr_2d_image_from_buffer` are sufficient.

**Comment by bashbaug** [comment]
Since https://github.com/KhronosGroup/OpenCL-Docs/pull/410 is merged and we now require OpenCL 3.0 implementations to report `cl_khr_image2d_from_buffer` when the optional feature is supported, nothing additional is required here and I am closing this issue.
