### ISSUE TITLE
Test Coverage for .rgba, .xyzw, and .s0123... swizzles

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-CTS#891]
This issue is to track a new test for vector swizzles, for the new .rgba swizzles in OpenCL C 3.0 and the existing .xyzw and .s0123... swizzles.  This was originally tracked by the item "Add a test for vector swizzles, including .xyzw, .rgbz, and .s012... swizzling" in #773.

One of the things we need to decide is how much test coverage we require for adequate test coverage.  For vectors up to size four, we can probably test all combinations of swizzles for all three swizzle formats(4^4 == 256), but for 8-component and 16-component vectors exhaustive testing is probably impossible.

**Comment by kpet** [comment]
I realise we didn't mean the same thing by "exhaustive" in the call. I was thinking of reading from all lanes and writing to all lanes for all types and sizes, not covering the gazillion permutations :).
