### ISSUE TITLE
Make sure support for read/write images isn't assumed on CL3

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#894]
With regards to the read-write image support, the test I mentioned in the call yesterday that we know is failing / being run unconditionally for a 3.0 device that optionally does not support read-write images is: `rw_image_access_qualifier` from `basic`. Since I couldn't see a ticket created for this yet I thought I'd put it here before I forget.

_Originally posted by @FranklandJack in https://github.com/KhronosGroup/OpenCL-CTS/issues/773#issuecomment-673955962_

**Comment by nikhiljnv** [comment]
Thanks @kpet  and @FranklandJack for filing the issue !!

I was looking through CTS today and also tried running read_write image tests.

Currently we are checking for OpenCL version < 2.0 to skip the test.
A couple of other tests that may need fixes are -
images/kernel_read_write/
images/samplerlessReads/

https://github.com/KhronosGroup/OpenCL-CTS/blob/ed50fcad2daf98887146122629a8a8e403ecef5c/test_conformance/images/kernel_read_write/main.cpp#L181

**Comment by FranklandJack** [comment]
I have upstreamed a local patch #922 skipping the `rw_image_access_qualifier` test in the cases that images aren't supported, or if on a 3.0 device images are supported but read-write images are optionally not supported. Hope this hasn't duplicated anyone else's work, but I thought since I had it I may as well upstream it.

**Comment by nikhiljnv** [comment]
@FranklandJack Thanks for the PR.
I started looking at this last week, but didn't have any changes ready.
There are couple of other tests I mentioned earlier. So, I will send out PR for those separately.
