### ISSUE TITLE
Validate values returned by OPENCL_C device queries

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#897]
CL_DEVICE_OPENCL_C_VERSION must return a version greater than `OpenCL C 1.2` on an OpenCL 3.0 implementation. It may return `OpenCL C 2.0` but then the implementation must support all the features of OpenCL C 2.0 (the test should check that the features are reported by the API, consistency with compiler macros is already tested by #762).

CL_DEVICE_OPENCL_C_VERSION must return the following on previous version
Versions|Value returned
------------|-------------------
2.x|`OpenCL C 2.0`
1.2|`OpenCL C 1.2`
1.1|`OpenCL C 1.1`
1.0|`OpenCL C 1.0` or `OpenCL C 1.1` (this looks suspicious since the query was introduced in 1.1)

CL_DEVICE_OPENCL_C_ALL_VERSIONS must return

Versions|Values returned
------------|-------------------
3.0|OpenCL C 1.0, 1.1, 1.2, 3.0. OpenCL C 2.0 may be returned as well if all required features are supported.
2.x|OpenCL C 1.0, 1.1, 1.2, 2.0
1.2|OpenCL C 1.0, 1.1, 1.2
1.1|OpenCL C 1.0, 1.1
1.0|OpenCL C 1.0

**Comment by neiltrevett** [comment]
364 897 899 – should be looked at together
