### ISSUE TITLE
Test 3.0 behaviour of program constructors/destructors support

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#903]
* `CL_PROGRAM_SCOPE_GLOBAL_CTORS_PRESENT` and `CL_PROGRAM_SCOPE_GLOBAL_DTORS_PRESENT` must return `CL_FALSE`
* `clSetProgramReleaseCallback` must return `CL_INVALID_OPERATION`

**Comment by bashbaug** [comment]
I've already implemented these checks in Part 2 of the API consistency test.  I hope to create a PR with it shortly.  Assigning to myself to avoid work duplication.

**Comment by bashbaug** [comment]
Fixed by #912.  Closing.
