### ISSUE TITLE
Does adding `volatile` to the 1.0 extension atomic names require testing changes?

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-CTS#908]
Legacy atomic functions such as `atom_add` had `volatile` added to their definition when they were renamed to `atomic_add` etc when they became core in 1.1.  The old names where never removed however, and OpenCL 3.0 removes the difference by [adding `volatile` to the legacy functions](https://github.com/KhronosGroup/OpenCL-Docs/issues/386).  The legacy names are also used in the CTS.

Does the addition of `volatile` require any testing changes?  My initial thought is "no".  The addition of volatile does not represent a testable change to the semantics of an OpenCL C kernel, yes the `volatile` keyword has meaning, but not in a way that guarantees a change in program behaviour.

I'm still opening this issue so as (a) people can give contrary opinions, and (b) I can revisit this myself.

**Comment by bashbaug** [comment]
I've been thinking about this and I can't think of any changes that would be needed for volatile vs. non-volatile.  I think we can just close this issue.

**Comment by alycm** [comment]
Yes, I agree.  I'll close the issue now.
