### ISSUE TITLE
Optionality of the generic address space for 3.0 conformance

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#909]
Generic address space is optional for devices >= 3.0.

The generic address space test already checks for the capabilities of the device, but there may be other tests that implicitly use the generic address space.

Those tests need to be skipped if generic address space is unsupported.

**Comment by alycm** [comment]
For the set of mandatory features, and SPIR-V tests, there are no remaining assumptions that generic address space is supported.   It is conceivable that some optional features that I don't have a means to test still make assumptions about generic address spaces.

**Comment by bashbaug** [comment]
Closing this issue.  We are not aware of any missing checks for the generic address space.
