### ISSUE TITLE
host_ptr semantics for clCreateBuffer/clCreateImage  when called without CL_​MEM_​USE_​HOST_​PTR or CL_​MEM_​COPY_​HOST_​PTR 

### ISSUE THREAD

**Issue by nikhiljnv** [KhronosGroup/OpenCL-CTS#918]
The spec currently says that clCreateBuffer or clCreateImage should return CL_​INVALID_​HOST_​PTR 

- if host_ptr is NULL and CL_​MEM_​USE_​HOST_​PTR or CL_​MEM_​COPY_​HOST_​PTR are set in flags 

- or if host_ptr is not NULL but CL_​MEM_​COPY_​HOST_​PTR or CL_​MEM_​USE_​HOST_​PTR are not set in flags.

However, CTS tests do not test or follow the second part of the spec above.
There are few places in CTS where these APIs are called with non NULL host_ptr, but without CL_​MEM_​USE_​HOST_​PTR or CL_​MEM_​COPY_​HOST_​PTR
https://github.com/KhronosGroup/OpenCL-CTS/blob/0ad8c9a9c02c9881ffce8bb9944136214db1f9e7/test_conformance/images/kernel_read_write/test_iterations.cpp#L1375

So, we have two options -

- Fix the spec to allow non-NULL host_ptr in absence of CL_​MEM_​USE_​HOST_​PTR or CL_​MEM_​COPY_​HOST_​PTR 

- Fix CTS to disallow passing non-NULL host-ptr in absence of CL_​MEM_​USE_​HOST_​PTR or CL_​MEM_​COPY_​HOST_​PTR  and potentially add a test to cover this scenario to ensure implementations return appropriate error.

**Comment by nikhiljnv** [comment]
Thanks Ben !!
Moved the issue to OpenCL-CTS.

**Comment by nikhiljnv** [comment]
Created PR for addressing this https://github.com/KhronosGroup/OpenCL-CTS/pull/1087/

**Comment by jlewis-austin** [comment]
#582 looks like a duplicate

**Comment by nikhiljnv** [comment]
Closing this as corresponding CTS change is merged as part of PR #1087
