### ISSUE TITLE
API queue_flush_on_release may call the destructor for clEventWrapper multiple times

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#936]
In the below snippet of this test, the lamda used may trigger the destructor for `clEventWrapper` to be called multiple times (`clReleaseEvent`).

```c
clEventWrapper event;

....

// Wait for kernel to execute since the queue must flush on release
    bool success = poll_until(2000, 50, [event]() {
        cl_int status;
        cl_int err = clGetEventInfo(event, CL_EVENT_COMMAND_EXECUTION_STATUS,
                                    sizeof(cl_int), &status, nullptr);
        if ((err != CL_SUCCESS) || (status != CL_COMPLETE))
        {
            return false;
        }
        return true;
    });
```

**Comment by kpet** [comment]
Right, I'll blame https://github.com/KhronosGroup/OpenCL-CTS/issues/465 but the event really ought to be passed by reference. I can prepare a PR if you don't have a fix already.

**Comment by Jeremy-Kemp** [comment]
I have a local (single character) change that does exactly that. I'll submit a PR when I get back from lunch.
