### ISSUE TITLE
Test compiler features macro need to be fixed in some areas 

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#979]
Add fixes for the following comments:
https://github.com/KhronosGroup/OpenCL-CTS/pull/762
https://github.com/KhronosGroup/OpenCL-CTS/pull/762#discussion_r494445361
https://github.com/KhronosGroup/OpenCL-CTS/pull/762#discussion_r494445638
https://github.com/KhronosGroup/OpenCL-CTS/pull/762#discussion_r494468614

**Comment by alycm** [comment]
I already had these changes locally when doing the review, just need https://github.com/KhronosGroup/OpenCL-CTS/pull/762 to merge and then I can submit a PR with them.

**Comment by gwawiork** [comment]
@alycm thanks for these changes
