### ISSUE TITLE
Test extended versioning as a core feature

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-CTS#992]
Currently the `computeinfo` tests for extended versioning only test `cl_khr_extended_versioning`.  These tests should also test the same features for 3.0 core, likely as a duplication due to manage the differences in `_KHR` suffices etc from the extension.

The extended versioning features are used by other 3.0 tests, so there is coverage, but it's easier to convince ourselves of complete coverage if we have a centralized test.

Caveats:
* `CL_DEVICE_OPENCL_C_NUMERIC_VERSION_KHR` is the extension but there is no `CL_DEVICE_OPENCL_C_NUMERIC_VERSION` in  core, so don't copy that part of testing.
* `CL_DEVICE_OPENCL_C_ALL_VERSIONS` is in core but there is no `CL_DEVICE_OPENCL_C_ALL_VERSIONS_KHR` in the extension, so that will require a brand new test.

**Comment by bashbaug** [comment]
FWIW, we do call and log all of the new queries as part of `computeinfo`.  This isn't comprehensive, and isn't automated like the queries for `cl_khr_extended_versioning`, but it does at least ensure that the queries are successful and can be manually inspected.
