### ISSUE TITLE
Validate value returned by CL_DEVICE_LATEST_CONFORMANCE_VERSION_PASSED

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#993]
Validate that the string matches `vYYYY-MM-DD-XX` where:
* YYYY-MM-DD is a valid date
* XX is a number

**Comment by alycm** [comment]
Given the specification doesn't make any statements about the form of the string returned for `CL_DEVICE_LATEST_CONFORMANCE_VERSION_PASSED` how can it be validated?

**Comment by kpet** [comment]
The specification may not define the form of the string but that doesn't prevent the CTS from putting constraints on it (as discussed in previous teleconferences). The CTS can know what a valid CTS version looks like :).
